"""Generate docs/mapping.md from a validated LayoutSpec.

Per KITT_ARCHITECTURE.md section 19: docs/mapping.md is a generated file and
should never be hand-maintained. This module is the only place that produces
it. `cli.py`'s `generate` subcommand writes the returned string to disk.
"""

from __future__ import annotations

from collections.abc import Iterable

from .model import ALTGR, BASE, SHIFT, SHIFT_ALTGR, LayoutSpec

_MODIFIER_COLUMN_TITLES = {
    BASE: "Base",
    SHIFT: "Shift",
    ALTGR: "AltGr",
    SHIFT_ALTGR: "Shift+AltGr",
}


def generate_mapping_doc(spec: LayoutSpec) -> str:
    """Render a human-readable Markdown mapping table for `spec`."""
    lines: list[str] = []

    lines.append(f"# {spec.metadata.name} — Mapping Reference")
    lines.append("")
    lines.append(
        "> Generated from `layout/kitt.uk-UA.yaml` by `python -m kittgen generate`. "
        "Do not edit this file by hand — edit the YAML source and regenerate."
    )
    lines.append("")
    lines.append(f"- **Layout ID:** `{spec.metadata.id}`")
    lines.append(f"- **Language:** {spec.metadata.language}")
    lines.append(f"- **Version:** {spec.metadata.version}")
    lines.append(f"- **Physical layout family:** `{spec.physical_layout.family}`")
    lines.append(f"- **Description:** {spec.metadata.description}")
    lines.append("")

    lines.append("## Key Mappings")
    lines.append("")
    lines.extend(_render_keys_table(spec))
    lines.append("")

    if spec.dead_keys:
        lines.append("## Dead Keys")
        lines.append("")
        lines.extend(_render_dead_keys(spec))
        lines.append("")

    lines.append("## Behavior")
    lines.append("")
    lines.append(f"- **Caps Lock:** {spec.behavior.caps_lock}")
    lines.append(f"- **Unicode normalization:** {spec.behavior.normalize_unicode}")
    lines.append(
        "- **Punctuation:** "
        + (
            "preserves QWERTY punctuation where possible"
            if spec.punctuation.preserve_qwerty_where_possible
            else "does not preserve QWERTY punctuation"
        )
    )
    lines.append("")

    return "\n".join(lines) + "\n"


def _render_keys_table(spec: LayoutSpec) -> list[str]:
    modifiers_present = _modifiers_in_use(
        outputs.by_modifier for outputs in spec.keys.values()
    )
    header = ["Physical Key"] + [_MODIFIER_COLUMN_TITLES[m] for m in modifiers_present]
    lines = [
        "| " + " | ".join(header) + " |",
        "| " + " | ".join(["---"] * len(header)) + " |",
    ]
    for physical_key in sorted(spec.keys):
        outputs = spec.keys[physical_key]
        row = [f"`{physical_key}`"]
        for modifier in modifiers_present:
            value = outputs.get(modifier)
            row.append(f"`{value}`" if value is not None else "—")
        lines.append("| " + " | ".join(row) + " |")
    return lines


def _render_dead_keys(spec: LayoutSpec) -> list[str]:
    lines: list[str] = []
    for dead_key_name in sorted(spec.dead_keys):
        dead_spec = spec.dead_keys[dead_key_name]
        lines.append(f"### `{dead_key_name}` (dead key)")
        lines.append("")

        alone_base = dead_spec.alone.get(BASE)
        alone_shift = dead_spec.alone.get(SHIFT)
        lines.append(
            f"Pressed alone (no following combination): base `{alone_base}`, "
            f"shift `{alone_shift}`."
        )
        lines.append("")

        modifiers_present = _modifiers_in_use(
            combo.by_modifier for combo in dead_spec.combinations.values()
        )
        header = ["Following Key"] + [
            _MODIFIER_COLUMN_TITLES[m] for m in modifiers_present
        ]
        lines.append("| " + " | ".join(header) + " |")
        lines.append("| " + " | ".join(["---"] * len(header)) + " |")
        for combo_key in sorted(dead_spec.combinations):
            combo = dead_spec.combinations[combo_key]
            row = [f"`{combo_key}`"]
            for modifier in modifiers_present:
                value = combo.get(modifier)
                row.append(f"`{value}`" if value is not None else "—")
            lines.append("| " + " | ".join(row) + " |")
        lines.append("")
    return lines


def _modifiers_in_use(all_by_modifier: Iterable[dict[str, str]]) -> list[str]:
    """Return recognized modifiers that appear in any of the given dicts, in
    canonical (BASE, SHIFT, ALTGR, SHIFT_ALTGR) order."""
    canonical_order = (BASE, SHIFT, ALTGR, SHIFT_ALTGR)
    seen: set[str] = set()
    for by_modifier in all_by_modifier:
        seen.update(by_modifier.keys())
    return [m for m in canonical_order if m in seen]
