"""Generate a Windows native keyboard-layout C source file (KBDTABLES) from a
validated `LayoutSpec`.

This module turns the platform-independent Kitt model (model.py) into the
concrete data tables the Windows kbdlayout DLL interface expects, as declared
in the Windows Driver Kit header:

    C:\\Program Files (x86)\\Windows Kits\\10\\Include\\10.0.19041.0\\um\\kbd.h

Generation strategy: override, don't rebuild
--------------------------------------------

Kitt is a Ukrainian mnemonic layout for a **Turkish Q physical keyboard**.
It changes what ~29 keys produce under base and Shift. It has no opinion
whatsoever about the other several hundred (VK, shift-state) pairs a real
keyboard layout has to define — AltGr output, Ctrl+Alt output, the numeric
keypad, the `"`/`é` key, the accent dead keys, the extended navigation
scan codes, and so on.

Earlier revisions of this generator built the tables bottom-up: emit a row
for each Ukrainian letter, then bolt on a hand-maintained list of "extra"
keys. That is structurally wrong, because a layout DLL's tables are the
**only** source Windows consults. A VK absent from every `aVkToWchars*`
table produces nothing; a shift state no `aModification[]` entry maps to a
Modification Number is dead. So every key nobody thought to list silently
broke, and each round of real-machine testing surfaced another one (first
digits and Space, then arrows and Insert/Delete/Home/End, then AltGr,
Ctrl+Alt, `"` and `é`).

This module therefore starts from the **complete** table set of the real
Windows-shipped Turkish Q driver (`turkish_q_reference.py`, dumped from
`KBDTUQ.DLL`) and applies Kitt's mapping as a set of targeted overrides:

  1. Copy every reference table verbatim — modifiers, `aVkToBits[]`, all six
     `VK_TO_WCHARS<n>` groups with their exact `Attributes` (CAPLOK /
     CAPLOKALTGR) flags, all three scan-code tables, the 59-entry dead-key
     table, and `fLocaleFlags` (which includes `KLLF_ALTGR` — omitting it,
     as an earlier revision did, disables AltGr wholesale).
  2. For each physical key in `layout/kitt.uk-UA.yaml`, replace **only**
     modification numbers 0 (base) and 1 (Shift) of that VK's existing row.
     Every other shift state on that row — AltGr, Shift+AltGr, Ctrl+Alt —
     keeps the real Turkish Q value, including any `WCH_DEAD` marker and
     its trailing DEADCHARS row.
  3. Turn Kitt's own dead key (Y) into `WCH_DEAD` for base and Shift, give
     it a DEADCHARS row carrying its identity characters, and append its
     combinations to the reference `DEADTRANS` table.

Safety invariants (KITT_ARCHITECTURE.md section 7) are satisfied by the
reference `aModification[]` table as-is: it already marks the pure-CTRL and
SHIFT+CTRL combinations `SHFT_INVALID`, so Ctrl+<letter> stays a shortcut.
This module copies that table unchanged rather than reinventing it.

This module does not modify model.py/parser.py/validation.py; it only
imports and consumes their public types.
"""

from __future__ import annotations

from dataclasses import dataclass, replace

from .model import BASE, SHIFT, DeadKeyCombination, DeadKeySpec, KeyOutputs, LayoutSpec
from .turkish_q_reference import (
    DEADCHARS_VK,
    SHFT_INVALID,
    WCH_DEAD,
    WCH_NONE,
    DeadKeyEntry,
    TurkishQReference,
    WcharGroup,
    WcharRow,
    load_reference,
)

GENERATED_FILE_WARNING = """\
/*
 * GENERATED FILE - DO NOT EDIT.
 *
 * This file was generated by `python -m kittgen generate` from
 * layout/kitt.uk-UA.yaml, overlaid on a dump of the real Windows-shipped
 * Turkish Q driver (kbdtuq_reference.json). Edit the YAML file and
 * regenerate instead of hand-editing this file (KITT_ARCHITECTURE.md
 * section 32: "generated tables clearly marked as generated").
 */
"""

# --- physical_key -> Windows virtual-key code ------------------------------
#
# Kitt's YAML uses physical_key identifiers (KeyA, KeyB, ..., plus a handful
# of Turkish-Q-specific names for keys that don't exist on a plain US
# keyboard: KeyCCedilla (Ç), KeyGBreve (Ğ), KeyISlash (İ), KeySCedilla (Ş)).
#
# The plain Latin letters map onto the standard VK_A..VK_Z constants, which
# are numerically equal to their ASCII uppercase letter codes (0x41-0x5A).
#
# The four Turkish-Q-specific physical keys' VK_OEM_* assignments come from
# the real Turkish Q driver dump, where each of these VKs is the row that
# actually produces that Turkish letter:
#   VK_OEM_1 (0xBA) -> base 0x015F 'ş', shift 0x015E 'Ş'
#   VK_OEM_4 (0xDB) -> base 0x011F 'ğ', shift 0x011E 'Ğ'
#   VK_OEM_5 (0xDC) -> base 0x00E7 'ç', shift 0x00C7 'Ç'
#   VK_OEM_7 (0xDE) -> base 0x0069 'i', shift 0x0130 'İ'
# This is authoritative (it is the real shipping driver), not a guess, and
# is re-verified at generation time: _resolve_override_targets() fails loudly
# if any of these VKs is missing from the reference tables.
PHYSICAL_KEY_TO_VK: dict[str, str] = {
    "KeyA": "VK_A", "KeyB": "VK_B", "KeyC": "VK_C", "KeyD": "VK_D",
    "KeyE": "VK_E", "KeyF": "VK_F", "KeyG": "VK_G", "KeyH": "VK_H",
    "KeyI": "VK_I", "KeyJ": "VK_J", "KeyK": "VK_K", "KeyL": "VK_L",
    "KeyM": "VK_M", "KeyN": "VK_N", "KeyO": "VK_O", "KeyP": "VK_P",
    "KeyQ": "VK_Q", "KeyR": "VK_R", "KeyS": "VK_S", "KeyT": "VK_T",
    "KeyU": "VK_U", "KeyV": "VK_V", "KeyW": "VK_W", "KeyX": "VK_X",
    "KeyY": "VK_Y", "KeyZ": "VK_Z",
    "KeyCCedilla": "VK_OEM_5",
    "KeyGBreve": "VK_OEM_4",
    "KeyISlash": "VK_OEM_7",
    "KeySCedilla": "VK_OEM_1",
}

# Numeric values for the VK_OEM_* names above, so a physical key can be
# resolved to the integer VK the reference tables are keyed by. (winuser.h
# has the same values; duplicating the four Kitt actually uses avoids
# parsing a system header at build time.)
VK_NAME_TO_CODE: dict[str, int] = {
    "VK_OEM_1": 0xBA,
    "VK_OEM_4": 0xDB,
    "VK_OEM_5": 0xDC,
    "VK_OEM_7": 0xDE,
}

# Modification numbers Kitt overrides. Per the reference `aModification[]`
# table ([0, 1, 3, 4, 15, 15, 2, 5]), modification number 0 is reached with
# no modifiers and 1 with Shift alone. Kitt deliberately touches only these
# two: everything else on a given row (AltGr = 3, Shift+AltGr = 4,
# Ctrl+Alt = 2, Shift+Ctrl+Alt = 5) keeps its real Turkish Q value.
MODNUM_BASE = 0
MODNUM_SHIFT = 1

MODIFIER_TO_MODNUM: dict[str, int] = {
    BASE: MODNUM_BASE,
    SHIFT: MODNUM_SHIFT,
}

C_TABLE_NAME_MODIFIERS = "kitt_CharModifiers"
C_TABLE_NAME_VK_TO_BITS = "kitt_VkToBits"
C_TABLE_NAME_VSC_TO_VK = "kitt_VscToVk"
C_TABLE_NAME_VSC_TO_VK_E0 = "kitt_VscToVk_E0"
C_TABLE_NAME_VSC_TO_VK_E1 = "kitt_VscToVk_E1"
C_TABLE_NAME_VK_TO_WCHARS_PREFIX = "kitt_VkToWchars"
C_TABLE_NAME_VK_TO_WCHAR_TABLE = "kitt_VkToWcharTable"
C_TABLE_NAME_DEAD_KEY = "kitt_DeadKey"
C_TABLE_NAME_KEY_NAMES = "kitt_KeyNames"
C_FUNCTION_NAME = "KbdLayerDescriptor"

# Modifier VK code -> the winuser.h name to emit for it, so the generated
# aVkToBits[] reads like Microsoft's own samples instead of raw numbers.
_MODIFIER_VK_NAMES: dict[int, str] = {
    0x10: "VK_SHIFT",
    0x11: "VK_CONTROL",
    0x12: "VK_MENU",
}

# Modifier bit value -> kbd.h name, likewise.
_MODIFIER_BIT_NAMES: dict[int, str] = {
    0x01: "KBDSHIFT",
    0x02: "KBDCTRL",
    0x04: "KBDALT",
}

# kbd.h Attributes flags, for readable generated output.
_ATTR_FLAG_NAMES: tuple[tuple[int, str], ...] = (
    (0x01, "CAPLOK"),
    (0x02, "SGCAPS"),
    (0x04, "CAPLOKALTGR"),
    (0x08, "KANALOK"),
    (0x80, "GRPSELTAP"),
)


class LayoutGenerationError(ValueError):
    """Raised when a Kitt layout cannot be expressed against the reference."""


@dataclass(frozen=True)
class _OverrideTarget:
    """A single Kitt override resolved against the reference tables."""

    physical_key: str
    vk: int
    vk_expr: str
    # modification number -> replacement wch value (code point or sentinel)
    replacements: dict[int, int | str]
    # Identity characters for a dead-key row's DEADCHARS entry, keyed the
    # same way. Empty for ordinary keys.
    dead_identities: dict[int, int]
    comment: str


def _c_vk_expr(vk_name: str) -> str:
    """Render a VK_* name as a C expression usable in a static initializer.

    winuser.h deliberately does NOT #define VK_A..VK_Z or VK_0..VK_9 (see
    its own comment: "VK_A - VK_Z are the same as ASCII 'A' - 'Z'"). Using
    the bare name (e.g. "VK_A") in generated C therefore fails to compile
    with C2065 "undeclared identifier" — confirmed by actually compiling
    the generated kitt_tables.c with MSVC. Every other VK_* constant (the
    function keys, VK_OEM_*, VK_SHIFT, etc.) IS #define'd in winuser.h and
    must be emitted as-is.
    """
    if len(vk_name) == 4 and vk_name.startswith("VK_") and vk_name[3].isalnum():
        return f"'{vk_name[3]}'"
    return vk_name


def _vk_expr_for_code(vk: int) -> str:
    """Render a raw virtual-key code as a readable C expression.

    Letters and digits become character literals (see `_c_vk_expr`); every
    other code is emitted as a plain hex byte, because the reference tables
    contain many VKs whose winuser.h names Kitt has no reason to track (OEM
    keys, media keys, IME keys, reserved codes) and a numeric literal is
    both correct and unambiguous.
    """
    ch = chr(vk)
    if ("A" <= ch <= "Z") or ("0" <= ch <= "9"):
        return f"'{ch}'"
    return f"0x{vk:02X}"


def _vk_code_for_physical_key(physical_key: str) -> int:
    """Resolve a YAML physical_key identifier to a numeric virtual-key code.

    `Y` (the dead-key trigger name used in kitt.uk-UA.yaml's `dead_keys`
    section) is a bare Latin letter identifier, not a `KeyY`-style name, so
    it is handled the same way KeyY would be.
    """
    vk_name = PHYSICAL_KEY_TO_VK.get(physical_key)
    if vk_name is None and len(physical_key) == 1 and physical_key.isalpha():
        vk_name = f"VK_{physical_key.upper()}"
    if vk_name is None:
        raise LayoutGenerationError(
            f"no known VK_* mapping for physical_key {physical_key!r}; "
            "add it to PHYSICAL_KEY_TO_VK in windows.py"
        )
    if vk_name in VK_NAME_TO_CODE:
        return VK_NAME_TO_CODE[vk_name]
    if len(vk_name) == 4 and vk_name[3].isalnum():
        return ord(vk_name[3].upper())
    raise LayoutGenerationError(
        f"physical_key {physical_key!r} maps to {vk_name!r}, whose numeric "
        "virtual-key code is unknown; add it to VK_NAME_TO_CODE in windows.py"
    )


def _vk_expr_for_physical_key(physical_key: str) -> str:
    """Resolve a YAML physical_key identifier to a VK_* C expression."""
    vk_name = PHYSICAL_KEY_TO_VK.get(physical_key)
    if vk_name is None and len(physical_key) == 1 and physical_key.isalpha():
        vk_name = f"VK_{physical_key.upper()}"
    if vk_name is None:
        raise LayoutGenerationError(
            f"no known VK_* mapping for physical_key {physical_key!r}; "
            "add it to PHYSICAL_KEY_TO_VK in windows.py"
        )
    return _c_vk_expr(vk_name)


def _wch_literal(value: int | str) -> str:
    """Render one `wch[]` element as a C expression."""
    if isinstance(value, str):
        if value not in (WCH_NONE, WCH_DEAD):
            raise LayoutGenerationError(f"unknown wch sentinel {value!r}")
        return value
    return f"0x{value:04X}"


def _attr_expr(attr: int) -> str:
    """Render an Attributes byte as OR'd kbd.h flag names."""
    if attr == 0:
        return "0"
    names = [name for bit, name in _ATTR_FLAG_NAMES if attr & bit]
    consumed = sum(bit for bit, _ in _ATTR_FLAG_NAMES if attr & bit)
    leftover = attr & ~consumed
    if leftover:
        names.append(f"0x{leftover:02X}")
    return " | ".join(names) if names else "0"


def _single_char(value: str, context: str) -> str:
    if len(value) != 1:
        raise LayoutGenerationError(
            f"{context}: expected a single Unicode scalar output, got {value!r}"
        )
    return value


def _resolve_override_targets(
    spec: LayoutSpec, reference: TurkishQReference
) -> list[_OverrideTarget]:
    """Turn the Kitt layout into per-VK override instructions.

    Fails loudly rather than silently dropping a key: if a physical key Kitt
    maps has no row in the real Turkish Q tables, there is nothing to
    override and the resulting layout would be missing that key entirely —
    exactly the class of bug this whole module exists to prevent.
    """
    targets: list[_OverrideTarget] = []
    claimed: dict[int, str] = {}

    for physical_key in sorted(spec.keys):
        outputs: KeyOutputs = spec.keys[physical_key]
        vk = _vk_code_for_physical_key(physical_key)
        _claim_vk(claimed, vk, physical_key)

        replacements: dict[int, int | str] = {}
        described: list[str] = []
        for modifier, modnum in MODIFIER_TO_MODNUM.items():
            char = outputs.get(modifier)
            if char is None:
                continue
            replacements[modnum] = ord(
                _single_char(char, f"{physical_key}.{modifier}")
            )
            described.append(f"{modifier}={char!r}")

        if not replacements:
            raise LayoutGenerationError(
                f"{physical_key} defines no base/shift output; a key that "
                "overrides nothing should simply be omitted from the YAML"
            )

        _require_reference_row(reference, vk, physical_key)
        targets.append(
            _OverrideTarget(
                physical_key=physical_key,
                vk=vk,
                vk_expr=_vk_expr_for_physical_key(physical_key),
                replacements=replacements,
                dead_identities={},
                comment=f"{physical_key}: {' '.join(described)}",
            )
        )

    for dead_key_name in sorted(spec.dead_keys):
        dead_spec: DeadKeySpec = spec.dead_keys[dead_key_name]
        vk = _vk_code_for_physical_key(dead_key_name)
        _claim_vk(claimed, vk, dead_key_name)

        replacements = {}
        identities: dict[int, int] = {}
        described = []
        for modifier, modnum in MODIFIER_TO_MODNUM.items():
            identity = dead_spec.alone.get(modifier)
            if identity is None:
                continue
            # The key itself becomes a dead key in this shift state...
            replacements[modnum] = WCH_DEAD
            # ...and the DEADCHARS row that follows carries the character
            # this dead key identifies as (and emits if no combination
            # matches). See _build_wchar_groups for how the pair is emitted.
            identities[modnum] = ord(
                _single_char(identity, f"dead_keys.{dead_key_name}.alone.{modifier}")
            )
            described.append(f"{modifier} identity={identity!r}")

        if not replacements:
            raise LayoutGenerationError(
                f"dead_keys.{dead_key_name}.alone defines no base/shift "
                "output; a dead key needs at least one identity character"
            )

        _require_reference_row(reference, vk, dead_key_name)
        targets.append(
            _OverrideTarget(
                physical_key=dead_key_name,
                vk=vk,
                vk_expr=_vk_expr_for_physical_key(dead_key_name),
                replacements=replacements,
                dead_identities=identities,
                comment=f"{dead_key_name}: dead key, {' '.join(described)}",
            )
        )

    return targets


def _claim_vk(claimed: dict[int, str], vk: int, physical_key: str) -> None:
    previous = claimed.get(vk)
    if previous is not None:
        raise LayoutGenerationError(
            f"physical keys {previous!r} and {physical_key!r} both resolve to "
            f"virtual key 0x{vk:02X}; each VK can only be overridden once"
        )
    claimed[vk] = physical_key


def _require_reference_row(
    reference: TurkishQReference, vk: int, physical_key: str
) -> None:
    if reference.find_row(vk) is None:
        raise LayoutGenerationError(
            f"physical key {physical_key!r} resolves to virtual key "
            f"0x{vk:02X}, which produces no characters in the reference "
            "Turkish Q layout. Kitt overrides existing rows rather than "
            "inventing them, so this key cannot be mapped without first "
            "establishing what the physical key really is."
        )


def _build_wchar_groups(
    reference: TurkishQReference, targets: list[_OverrideTarget]
) -> tuple[list[WcharGroup], list[str]]:
    """Apply every override onto a copy of the reference `VK_TO_WCHARS` groups.

    Returns the rewritten groups plus a per-row comment list is not needed
    here; comments are attached during rendering via `overrides_by_vk`.
    """
    overrides = {target.vk: target for target in targets}
    applied: list[str] = []
    new_groups: list[WcharGroup] = []

    for group in reference.wchar_groups:
        rows: list[WcharRow] = []
        index = 0
        while index < len(group.rows):
            row = group.rows[index]
            following = (
                group.rows[index + 1] if index + 1 < len(group.rows) else None
            )
            has_deadchars = following is not None and following.is_deadchars

            target = overrides.get(row.vk) if isinstance(row.vk, int) else None
            if target is None:
                rows.append(row)
                index += 1
                continue

            new_wch = list(row.wch)
            for modnum, value in target.replacements.items():
                if modnum >= group.n_modifications:
                    raise LayoutGenerationError(
                        f"{target.physical_key} needs modification number "
                        f"{modnum}, but virtual key 0x{target.vk:02X} lives in "
                        f"a {group.n_modifications}-shift-state group"
                    )
                new_wch[modnum] = value

            rows.append(replace(row, wch=tuple(new_wch)))
            applied.append(target.physical_key)

            # Rebuild the DEADCHARS row for this VK. Three cases:
            #   - Kitt made this key a dead key: emit (or extend) a DEADCHARS
            #     row carrying Kitt's identity characters, preserving any the
            #     reference already had for untouched shift states.
            #   - The reference row was already partly dead (e.g. Ş's AltGr
            #     acute accent): keep its DEADCHARS row verbatim.
            #   - Neither: no DEADCHARS row.
            if target.dead_identities:
                base_identity: list[int | str] = (
                    list(following.wch)
                    if has_deadchars and following is not None
                    else [WCH_NONE] * group.n_modifications
                )
                for modnum, identity in target.dead_identities.items():
                    base_identity[modnum] = identity
                rows.append(
                    WcharRow(
                        vk=DEADCHARS_VK,
                        attr=following.attr if has_deadchars and following else 0,
                        wch=tuple(base_identity),
                    )
                )
            elif has_deadchars and following is not None:
                rows.append(following)

            index += 2 if has_deadchars else 1

        new_groups.append(replace(group, rows=tuple(rows)))

    missing = {t.physical_key for t in targets} - set(applied)
    if missing:
        raise LayoutGenerationError(
            "internal error: overrides were resolved but never applied for "
            f"{sorted(missing)}"
        )

    return new_groups, applied


def _build_dead_key_entries(
    spec: LayoutSpec, reference: TurkishQReference
) -> list[tuple[DeadKeyEntry, str]]:
    """Reference `DEADTRANS` rows first, then Kitt's own, with comments.

    Windows identifies "which dead key" a DEADKEY row belongs to by the
    dead key's *identity* character — the value in its DEADCHARS row for the
    shift state that was active — see kbd.h's DEADTRANS macro:
    `dwBoth = MAKELONG(ch, accent)`, where `accent` is that identifying
    character and `ch` is the character physically typed next.

    Kitt's Y dead key has a distinct identity per shift state ('й' unshifted,
    'Й' shifted), so each combination contributes one row per shift state:
    Shift+A after Shift+Y types 'А' against accent 'Й' and composes to 'Я',
    while a after y types 'а' against 'й' and composes to 'я'. Mixing the
    two (as an earlier revision did, using the unshifted identity for every
    row) leaves the shifted sequences unmatched at runtime.
    """
    entries: list[tuple[DeadKeyEntry, str]] = []

    for entry in reference.dead_keys:
        entries.append(
            (
                entry,
                f"Turkish Q: {chr(entry.accent)!r} + {chr(entry.ch)!r} "
                f"-> {chr(entry.composed)!r}",
            )
        )

    seen: set[tuple[int, int]] = {(e.ch, e.accent) for e, _ in entries}

    for dead_key_name in sorted(spec.dead_keys):
        dead_spec: DeadKeySpec = spec.dead_keys[dead_key_name]

        for combo_key in sorted(dead_spec.combinations):
            combo: DeadKeyCombination = dead_spec.combinations[combo_key]
            following_outputs = spec.keys.get(combo_key)
            for modifier, composed_char in sorted(combo.by_modifier.items()):
                identity = dead_spec.alone.get(modifier)
                if identity is None:
                    # This dead key is not dead in this shift state, so there
                    # is no accent to compose against.
                    continue
                following_char = (
                    following_outputs.get(modifier)
                    if following_outputs is not None
                    else None
                )
                if following_char is None:
                    # The following physical key has no Kitt output under this
                    # modifier (e.g. it is itself a dead-key trigger, or is not
                    # remapped) — nothing to compose against, so skip rather
                    # than guess.
                    continue

                ch = ord(_single_char(following_char, f"{combo_key}.{modifier}"))
                accent = ord(
                    _single_char(
                        identity, f"dead_keys.{dead_key_name}.alone.{modifier}"
                    )
                )
                composed = ord(
                    _single_char(
                        composed_char,
                        f"dead_keys.{dead_key_name}.combinations."
                        f"{combo_key}.{modifier}",
                    )
                )

                if (ch, accent) in seen:
                    raise LayoutGenerationError(
                        f"dead-key combination {dead_key_name} + {combo_key}."
                        f"{modifier} collides with an existing DEADTRANS entry "
                        f"for accent U+{accent:04X} + char U+{ch:04X}"
                    )
                seen.add((ch, accent))

                entries.append(
                    (
                        DeadKeyEntry(ch=ch, accent=accent, composed=composed, flags=1),
                        f"Kitt: {dead_key_name} + {combo_key}.{modifier} "
                        f"({following_char!r}) -> {composed_char!r}",
                    )
                )

    return entries


def generate_kbdtables_source(
    spec: LayoutSpec, reference: TurkishQReference | None = None
) -> str:
    """Generate a complete .c source file implementing KBDTABLES for `spec`.

    The returned string is a self-contained translation unit: it includes
    <windows.h> and "kbd.h", defines every table KBDTABLES references, and
    exports `KbdLayerDescriptor()` returning a pointer to the populated
    struct, matching the standard pattern used by Microsoft's WDK keyboard
    layout samples (kbdxx.c).

    `reference` defaults to the bundled Turkish Q driver dump; it is a
    parameter so tests can supply a trimmed fixture.
    """
    ref = reference if reference is not None else load_reference()

    targets = _resolve_override_targets(spec, ref)
    groups, _applied = _build_wchar_groups(ref, targets)
    dead_entries = _build_dead_key_entries(spec, ref)
    overrides_by_vk = {t.vk: t for t in targets}

    lines: list[str] = []
    lines.append(GENERATED_FILE_WARNING)
    lines.append(
        f"// Layout: {spec.metadata.name} ({spec.metadata.id}), "
        f"version {spec.metadata.version}"
    )
    lines.append(f"// Language: {spec.metadata.language}")
    lines.append(f"// Description: {spec.metadata.description}")
    lines.append("//")
    lines.append(
        "// Base tables: the real Windows-shipped Turkish Q driver "
        "(KBDTUQ.DLL),"
    )
    lines.append(
        f"// copied verbatim. Kitt overrides base/Shift on {len(targets)} "
        "virtual keys;"
    )
    lines.append(
        "// every other key and shift state (AltGr, Ctrl+Alt, dead-key "
        "accents,"
    )
    lines.append("// the keypad, navigation keys) keeps its Turkish Q behavior.")
    lines.append("")
    lines.append("#include <windows.h>")
    lines.append('#include "kbd.h"')
    lines.append("")

    lines.extend(_render_vk_to_bits(ref))
    lines.append("")
    lines.extend(_render_modifiers(ref))
    lines.append("")
    lines.extend(_render_wchar_groups(groups, overrides_by_vk))
    lines.append("")
    lines.extend(_render_vk_to_wchar_table(groups))
    lines.append("")
    lines.extend(_render_dead_keys(dead_entries))
    lines.append("")
    lines.extend(_render_scancode_to_vk(ref))
    lines.append("")
    lines.extend(
        _render_extended_scancode_table(
            C_TABLE_NAME_VSC_TO_VK_E0,
            ref.vsc_to_vk_e0,
            "aVscToVk_E0[]: 0xE0-prefixed scan codes (arrow keys, Insert/"
            "Delete/Home/End/PageUp/PageDown, right Ctrl/Alt, numpad Enter/"
            "Divide, media keys). Copied from the Turkish Q driver. Leaving "
            "this table empty makes every extended key stop working while "
            "Kitt is active — confirmed on a real machine.",
        )
    )
    lines.append("")
    lines.extend(
        _render_extended_scancode_table(
            C_TABLE_NAME_VSC_TO_VK_E1,
            ref.vsc_to_vk_e1,
            "aVscToVk_E1[]: 0xE1-prefixed scan codes (Pause/Break).",
        )
    )
    lines.append("")
    lines.extend(_render_key_names())
    lines.append("")
    lines.extend(_render_kbdtables(ref, has_dead_keys=bool(dead_entries)))
    lines.append("")
    lines.extend(_render_descriptor_function())
    lines.append("")

    return "\n".join(lines) + "\n"


def _render_vk_to_bits(ref: TurkishQReference) -> list[str]:
    lines = [
        "// aVkToBits[]: real modifier keys -> modifier bitmask, copied from",
        "// the Turkish Q driver. bit 0 = SHIFT, bit 1 = CTRL, bit 2 = ALT.",
        f"static VK_TO_BIT {C_TABLE_NAME_VK_TO_BITS}[] = {{",
    ]
    for entry in ref.vk_to_bits:
        vk_name = _MODIFIER_VK_NAMES.get(entry.vk, f"0x{entry.vk:02X}")
        bit_name = _MODIFIER_BIT_NAMES.get(entry.mod_bits, f"0x{entry.mod_bits:02X}")
        lines.append(f"    {{ {vk_name}, {bit_name} }},")
    lines.append("    { 0, 0 },")
    lines.append("};")
    return lines


def _render_modifiers(ref: TurkishQReference) -> list[str]:
    # Human-readable description of each (CTRL, ALT, SHIFT) index.
    combo_names = [
        "<none>", "SHIFT", "ALT", "SHIFT ALT",
        "CTRL", "SHIFT CTRL", "CTRL ALT", "SHIFT CTRL ALT",
    ]
    lines = [
        "// aModification[]: (CTRL,ALT,SHIFT) bit combination -> Modification",
        "// Number (index into each VK_TO_WCHARS*.wch[]). Copied verbatim from",
        "// the Turkish Q driver, which already satisfies Kitt's safety",
        "// invariant (KITT_ARCHITECTURE.md section 7): the pure-CTRL and",
        "// SHIFT+CTRL states are SHFT_INVALID, so Ctrl+<letter> stays an",
        "// ordinary Windows shortcut instead of emitting a Ukrainian letter.",
        f"static MODIFIERS {C_TABLE_NAME_MODIFIERS} = {{",
        f"    {C_TABLE_NAME_VK_TO_BITS},",
        f"    {ref.max_mod_bits},  // wMaxModBits",
        "    {",
    ]
    for index, value in enumerate(ref.modification_numbers):
        name = combo_names[index] if index < len(combo_names) else "?"
        rendered = "SHFT_INVALID" if value == SHFT_INVALID else str(value)
        lines.append(f"        {rendered},  // {index:03b} {name}")
    lines.append("    },")
    lines.append("};")
    return lines


def _group_table_name(n_modifications: int) -> str:
    return f"{C_TABLE_NAME_VK_TO_WCHARS_PREFIX}{n_modifications}"


def _render_wchar_groups(
    groups: list[WcharGroup], overrides_by_vk: dict[int, _OverrideTarget]
) -> list[str]:
    lines: list[str] = []
    for group_index, group in enumerate(groups):
        n = group.n_modifications
        if group_index:
            lines.append("")
        lines.append(
            f"// aVkToWchars{n}[]: every VK with {n} shift state"
            f"{'s' if n != 1 else ''}, from the Turkish Q driver, with Kitt's"
        )
        lines.append(
            "// base/Shift overrides applied. Columns follow aModification[]:"
        )
        lines.append(
            "//   [0] base  [1] SHIFT  [2] CTRL+ALT  [3] ALTGR  "
            "[4] SHIFT+ALTGR  [5] SHIFT+CTRL+ALT"
        )
        lines.append(f"static VK_TO_WCHARS{n} {_group_table_name(n)}[] = {{")
        for row in group.rows:
            wch = ", ".join(_wch_literal(value) for value in row.wch)
            if row.is_deadchars:
                # kbd.h: VirtualKey == -1 marks a "dead chars for the previous
                # entry" row. Emitted as 0xFF because the struct field is a
                # BYTE and MSVC rejects a negative initializer there.
                lines.append(
                    f"    {{ 0xFF, {_attr_expr(row.attr)}, {{ {wch} }} }},"
                    "  // dead chars for the row above"
                )
                continue
            target = overrides_by_vk.get(row.vk) if isinstance(row.vk, int) else None
            comment = f"  // {target.comment}" if target is not None else ""
            vk_expr = (
                target.vk_expr
                if target is not None
                else _vk_expr_for_code(int(row.vk))
            )
            lines.append(
                f"    {{ {vk_expr}, {_attr_expr(row.attr)}, {{ {wch} }} }},{comment}"
            )
        zeros = ", ".join(["0"] * n)
        lines.append(f"    {{ 0, 0, {{ {zeros} }} }},  // terminator")
        lines.append("};")
    return lines


def _render_vk_to_wchar_table(groups: list[WcharGroup]) -> list[str]:
    lines = [
        "// aVkToWcharTable[]: every VK_TO_WCHARS group above, tagged with its",
        "// shift-state count so Windows knows how wide each row's wch[] is.",
        f"static VK_TO_WCHAR_TABLE {C_TABLE_NAME_VK_TO_WCHAR_TABLE}[] = {{",
    ]
    for group in groups:
        n = group.n_modifications
        name = _group_table_name(n)
        lines.append(
            f"    {{ (PVK_TO_WCHARS1)(void*){name}, {n}, "
            f"sizeof(VK_TO_WCHARS{n}) }},"
        )
    lines.append("    { NULL, 0, 0 },  // terminator")
    lines.append("};")
    return lines


def _render_dead_keys(entries: list[tuple[DeadKeyEntry, str]]) -> list[str]:
    lines = [
        "// aDeadKey[]: dead-key combination -> composed character.",
        "// dwBoth = MAKELONG(following_char, accent_char): low word is the",
        "// character typed after the dead key, high word is the dead key's",
        "// own identity character (from its DEADCHARS row above).",
        "// The Turkish Q accents (circumflex, acute, diaeresis, grave, tilde)",
        "// are preserved as-is; Kitt's own Y combinations are appended.",
        f"static DEADKEY {C_TABLE_NAME_DEAD_KEY}[] = {{",
    ]
    for entry, comment in entries:
        flags = "DKF_DEAD" if entry.flags & 1 else f"0x{entry.flags:04X}"
        lines.append(
            f"    DEADTRANS(0x{entry.ch:04X}, 0x{entry.accent:04X}, "
            f"0x{entry.composed:04X}, {flags}),  // {comment}"
        )
    lines.append("    DEADTRANS(0, 0, 0, 0),  // terminator")
    lines.append("};")
    return lines


def _render_scancode_to_vk(ref: TurkishQReference) -> list[str]:
    lines = [
        "// aVscToVk[]: scan-code -> virtual-key table, copied from the Turkish",
        "// Q driver. Kitt does not remap physical key positions, only what",
        "// each VK produces, so this is the Turkish Q ISO (105-key) table",
        "// unchanged.",
        f"static USHORT {C_TABLE_NAME_VSC_TO_VK}[] = {{",
    ]
    # pusVSCtoVK is indexed directly by scan code (Windows reads
    # pusVSCtoVK[vsc]), so index 0 must correspond to scan code 0x00, not
    # scan code 0x01 — confirmed by loading this generator's own compiled
    # DLL and reading back pusVSCtoVK, which caught an earlier off-by-one
    # here (index 0 held scan code 1's VK, shifting every entry by one).
    table = {entry.vsc: entry.vk for entry in ref.vsc_to_vk}
    max_scancode = max(table)
    for scancode in range(0, max_scancode + 1):
        vk = table.get(scancode)
        vk_expr = _vk_expr_for_code(vk) if vk is not None else "0"
        lines.append(f"    /* 0x{scancode:02X} */ {vk_expr},")
    lines.append("};")
    return lines


def _render_extended_scancode_table(
    table_name: str, entries: tuple, comment: str
) -> list[str]:
    lines = [
        f"// {comment}",
        f"static VSC_VK {table_name}[] = {{",
    ]
    for entry in entries:
        lines.append(
            f"    {{ 0x{entry.vsc:02X}, {_vk_expr_for_code(entry.vk)} }},"
        )
    lines.append("    { 0, 0 },  // terminator")
    lines.append("};")
    return lines


def _render_key_names() -> list[str]:
    # Minimal key-name table: Windows falls back to defaults for anything not
    # listed, and Kitt does not rename any key, so this is intentionally
    # empty (terminator-only), matching kbd.h's documented "table" shape.
    lines = [
        "// aKeyNames[]: display names for keys shown in OS key-name UI.",
        "// Kitt does not rename any key, so this table only has the",
        "// required NULL terminator.",
        f"static VSC_LPWSTR {C_TABLE_NAME_KEY_NAMES}[] = {{",
        "    { 0, NULL },",
        "};",
    ]
    return lines


def _render_kbdtables(ref: TurkishQReference, *, has_dead_keys: bool) -> list[str]:
    dead_key_field = C_TABLE_NAME_DEAD_KEY if has_dead_keys else "NULL"
    # fLocaleFlags is copied from the Turkish Q driver rather than
    # reconstructed. Its low word carries the KLLF_* layout attributes and
    # its high word the KBD_VERSION. The real driver sets KLLF_ALTGR
    # (0x0001): without it Windows does not treat right-Alt as AltGr at all,
    # so every AltGr column in the tables above would be unreachable — the
    # exact symptom reported from real-machine testing.
    low = ref.locale_flags & 0xFFFF
    high = (ref.locale_flags >> 16) & 0xFFFF
    flag_names = []
    if low & 0x0001:
        flag_names.append("KLLF_ALTGR")
    if low & 0x0002:
        flag_names.append("KLLF_SHIFTLOCK")
    if low & 0x0004:
        flag_names.append("KLLF_LRM_RLM")
    leftover = low & ~0x0007
    if leftover:
        flag_names.append(f"0x{leftover:04X}")
    low_expr = " | ".join(flag_names) if flag_names else "0"
    high_expr = "KBD_VERSION" if high == 1 else str(high)

    lines = [
        "// Root KBDTABLES struct: ties every table above together. Returned",
        f"// by {C_FUNCTION_NAME}() below, per the standard WDK keyboard-",
        "// layout DLL export contract.",
        "static KBDTABLES kitt_KbdTables = {",
        f"    &{C_TABLE_NAME_MODIFIERS},              // pCharModifiers",
        f"    {C_TABLE_NAME_VK_TO_WCHAR_TABLE},        // pVkToWcharTable",
        f"    {dead_key_field},                        // pDeadKey",
        f"    {C_TABLE_NAME_KEY_NAMES},                // pKeyNames",
        "    NULL,                                    // pKeyNamesExt",
        "    NULL,                                    // pKeyNamesDead",
        f"    {C_TABLE_NAME_VSC_TO_VK},                // pusVSCtoVK",
        f"    (BYTE)(sizeof({C_TABLE_NAME_VSC_TO_VK}) / "
        f"sizeof({C_TABLE_NAME_VSC_TO_VK}[0])),  // bMaxVSCtoVK",
        f"    {C_TABLE_NAME_VSC_TO_VK_E0},             // pVSCtoVK_E0",
        f"    {C_TABLE_NAME_VSC_TO_VK_E1},             // pVSCtoVK_E1",
        f"    MAKELONG({low_expr}, {high_expr}),         // fLocaleFlags",
        "    0,                                       // nLgMax (no ligatures)",
        "    0,                                       // cbLgEntry",
        "    NULL,                                    // pLigature",
        f"    {ref.dw_type},                                       // dwType",
        f"    {ref.dw_sub_type},                                       // dwSubType",
        "};",
    ]
    return lines


def _render_descriptor_function() -> list[str]:
    lines = [
        "// Standard WDK keyboard-layout DLL export: returns the KBDTABLES",
        "// struct describing this layout. See kbd.def/.def export file for",
        "// the corresponding EXPORTS entry.",
        f"__declspec(dllexport) PKBDTABLES WINAPI {C_FUNCTION_NAME}(VOID)",
        "{",
        "    return &kitt_KbdTables;",
        "}",
        "",
    ]
    return lines
