"""Generate a Windows native keyboard-layout C source file (KBDTABLES) from a
validated `LayoutSpec`.

This module turns the platform-independent Kitt model (model.py) into the
concrete data tables the Windows kbdlayout DLL interface expects, as declared
in the Windows Driver Kit header:

    C:\\Program Files (x86)\\Windows Kits\\10\\Include\\10.0.19041.0\\um\\kbd.h

It follows the standard structure used by Microsoft's own kbdxx.c samples
(e.g. kbdus.c): an `aVkToBits[]` / `aModification[]` modifier table, one or
more `aVkToWchars*[]` tables grouped by shift-state count, an `aVSCtoVK[]`
scan-code table, an optional `aDeadKey[]` table, and a root `KBDTABLES`
struct returned by an exported `KbdLayerDescriptor()` function.

Scope for Kitt (KITT_ARCHITECTURE.md section 8):
  - Kitt only uses two modifier states: base and shift. It does not use
    AltGr/KANA/etc.
  - Ctrl (alone or combined with Alt) must keep behaving like a normal
    Windows shortcut modifier, not emit letters (architecture section 7,
    "Safety invariants": "Ctrl shortcuts should not unexpectedly emit
    letters"). This is implemented by marking the CTRL and CTRL+ALT
    modification-bit combinations as SHFT_INVALID in `aModification[]`,
    exactly like Microsoft's own US layout does for undefined shift states.
  - The scan-code -> virtual-key table is the standard PC/AT-101 layout
    (the same one used by kbdus.c and friends): Kitt changes what each VK
    *produces*, not which physical key maps to which VK. This keeps every
    physical key's position identical to a normal US/ISO layout.

This module does not modify model.py/parser.py/validation.py; it only
imports and consumes their public types.
"""

from __future__ import annotations

from dataclasses import dataclass

from .model import BASE, SHIFT, DeadKeyCombination, DeadKeySpec, KeyOutputs, LayoutSpec

GENERATED_FILE_WARNING = """\
/*
 * GENERATED FILE - DO NOT EDIT.
 *
 * This file was generated by `python -m kittgen generate` from
 * layout/kitt.uk-UA.yaml. Edit that YAML file and regenerate instead of
 * hand-editing this file (KITT_ARCHITECTURE.md section 32: "generated
 * tables clearly marked as generated").
 */
"""

# --- physical_key -> Windows virtual-key constant --------------------------
#
# Kitt's YAML uses physical_key identifiers (KeyA, KeyB, ..., plus a handful
# of Turkish-Q-specific names for keys that don't exist on a plain US
# keyboard: KeyCCedilla (Ç), KeyGBreve (Ğ), KeyISlash (İ), KeySCedilla (Ş)).
#
# The plain Latin letters map onto the standard VK_A..VK_Z constants, which
# are numerically equal to their ASCII uppercase letter codes (0x41-0x5A) on
# Windows and are not '#define'd in kbd.h/winuser.h under a different value,
# so this mapping is not in question.
#
# The four Turkish-Q-specific physical keys' VK_OEM_* assignments were
# confirmed empirically by loading the real Windows-shipped Turkish Q driver
# (C:\Windows\System32\KBDTUQ.DLL) via LoadLibraryExW(..., DONT_RESOLVE_DLL_REFERENCES)
# and reading its exported KbdLayerDescriptor()->pVkToWcharTable directly:
#   VK_OEM_1 (0xBA) -> base 0x015F 'ş', shift 0x015E 'Ş'
#   VK_OEM_4 (0xDB) -> base 0x011F 'ğ', shift 0x011E 'Ğ'
#   VK_OEM_5 (0xDC) -> base 0x00E7 'ç', shift 0x00C7 'Ç'
#   VK_OEM_7 (0xDE) -> base 0x0069 'i', shift 0x0130 'İ'
# This is authoritative (it is the real shipping driver), not a guess.
PHYSICAL_KEY_TO_VK: dict[str, str] = {
    "KeyA": "VK_A", "KeyB": "VK_B", "KeyC": "VK_C", "KeyD": "VK_D",
    "KeyE": "VK_E", "KeyF": "VK_F", "KeyG": "VK_G", "KeyH": "VK_H",
    "KeyI": "VK_I", "KeyJ": "VK_J", "KeyK": "VK_K", "KeyL": "VK_L",
    "KeyM": "VK_M", "KeyN": "VK_N", "KeyO": "VK_O", "KeyP": "VK_P",
    "KeyQ": "VK_Q", "KeyR": "VK_R", "KeyS": "VK_S", "KeyT": "VK_T",
    "KeyU": "VK_U", "KeyV": "VK_V", "KeyW": "VK_W", "KeyX": "VK_X",
    "KeyY": "VK_Y", "KeyZ": "VK_Z",
    # Confirmed against KBDTUQ.DLL: VK_OEM_5 produces ç/Ç.
    "KeyCCedilla": "VK_OEM_5",
    # Confirmed against KBDTUQ.DLL: VK_OEM_4 produces ğ/Ğ.
    "KeyGBreve": "VK_OEM_4",
    # Confirmed against KBDTUQ.DLL: VK_OEM_7 produces i/İ.
    "KeyISlash": "VK_OEM_7",
    # Confirmed against KBDTUQ.DLL: VK_OEM_1 produces ş/Ş.
    "KeySCedilla": "VK_OEM_1",
}

# --- standard PC/AT-101 scan-code -> virtual-key table ----------------------
#
# Kitt does not change which physical key position maps to which VK: it only
# changes what each VK produces (via aVkToWchars*). This table was verified
# against the real Windows-shipped Turkish Q driver (KBDTUQ.DLL) by loading
# it with LoadLibraryExW(..., DONT_RESOLVE_DLL_REFERENCES) and reading its
# exported KbdLayerDescriptor()->pusVSCtoVK directly. This matters because a
# Turkish Q keyboard is a 105-key ISO layout (it has an extra key at 0x56,
# left of Z, that a 104-key US-ANSI layout does not), which shifts scan
# codes 0x2B and 0x33-0x35 relative to a plain US-ANSI table:
#   0x2B -> VK_OEM_COMMA (not VK_OEM_5)
#   0x33 -> VK_OEM_2     (not VK_OEM_COMMA)   -- Ö
#   0x34 -> VK_OEM_5     (not VK_OEM_PERIOD)  -- Ç
#   0x35 -> VK_OEM_PERIOD (not VK_OEM_2)
# Values are (scan_code, vk_name) pairs; scan_code is the standard "make
# code" byte (Set 1).
STANDARD_SCANCODE_TO_VK: tuple[tuple[int, str], ...] = (
    (0x01, "VK_ESCAPE"),
    (0x02, "VK_1"), (0x03, "VK_2"), (0x04, "VK_3"), (0x05, "VK_4"),
    (0x06, "VK_5"), (0x07, "VK_6"), (0x08, "VK_7"), (0x09, "VK_8"),
    (0x0A, "VK_9"), (0x0B, "VK_0"),
    (0x0C, "VK_OEM_8"),  # Turkish Q: 0x0C is VK_OEM_8 (*/? position), not VK_OEM_MINUS
    (0x0D, "VK_OEM_MINUS"),  # Turkish Q: 0x0D is VK_OEM_MINUS, not VK_OEM_PLUS
    (0x0E, "VK_BACK"),
    (0x0F, "VK_TAB"),
    (0x10, "VK_Q"), (0x11, "VK_W"), (0x12, "VK_E"), (0x13, "VK_R"),
    (0x14, "VK_T"), (0x15, "VK_Y"), (0x16, "VK_U"), (0x17, "VK_I"),
    (0x18, "VK_O"), (0x19, "VK_P"),
    (0x1A, "VK_OEM_4"),  # Ğ
    (0x1B, "VK_OEM_6"),  # Ü
    (0x1C, "VK_RETURN"),
    (0x1D, "VK_LCONTROL"),
    (0x1E, "VK_A"), (0x1F, "VK_S"), (0x20, "VK_D"), (0x21, "VK_F"),
    (0x22, "VK_G"), (0x23, "VK_H"), (0x24, "VK_J"), (0x25, "VK_K"),
    (0x26, "VK_L"),
    (0x27, "VK_OEM_1"),  # Ş
    (0x28, "VK_OEM_7"),  # İ
    (0x29, "VK_OEM_3"),  # '"' key, left of '1'
    (0x2A, "VK_LSHIFT"),
    (0x2B, "VK_OEM_COMMA"),  # Turkish Q ISO: '<>' key right of Şin, not VK_OEM_5
    (0x2C, "VK_Z"), (0x2D, "VK_X"), (0x2E, "VK_C"), (0x2F, "VK_V"),
    (0x30, "VK_B"), (0x31, "VK_N"), (0x32, "VK_M"),
    (0x33, "VK_OEM_2"),      # Ö (Turkish Q ISO shift vs. US-ANSI)
    (0x34, "VK_OEM_5"),      # Ç (Turkish Q ISO shift vs. US-ANSI)
    (0x35, "VK_OEM_PERIOD"), # Turkish Q ISO shift vs. US-ANSI
    (0x36, "VK_RSHIFT"),
    (0x37, "VK_MULTIPLY"),
    (0x38, "VK_LMENU"),
    (0x39, "VK_SPACE"),
    (0x3A, "VK_CAPITAL"),
    (0x3B, "VK_F1"), (0x3C, "VK_F2"), (0x3D, "VK_F3"), (0x3E, "VK_F4"),
    (0x3F, "VK_F5"), (0x40, "VK_F6"), (0x41, "VK_F7"), (0x42, "VK_F8"),
    (0x43, "VK_F9"), (0x44, "VK_F10"),
    (0x45, "VK_NUMLOCK"),
    (0x46, "VK_SCROLL"),
    (0x47, "VK_NUMPAD7"), (0x48, "VK_NUMPAD8"), (0x49, "VK_NUMPAD9"),
    (0x4A, "VK_SUBTRACT"),
    (0x4B, "VK_NUMPAD4"), (0x4C, "VK_NUMPAD5"), (0x4D, "VK_NUMPAD6"),
    (0x4E, "VK_ADD"),
    (0x4F, "VK_NUMPAD1"), (0x50, "VK_NUMPAD2"), (0x51, "VK_NUMPAD3"),
    (0x52, "VK_NUMPAD0"),
    (0x53, "VK_DECIMAL"),
    (0x56, "VK_OEM_102"),  # extra ISO key, left of Z ('<>')
    (0x57, "VK_F11"), (0x58, "VK_F12"),
)

# The four Turkish-Q-specific keys occupy scan-code positions that already
# exist in the standard table above (they are OEM punctuation positions on a
# US keyboard, relabeled on a Turkish Q keyboard). No extra scan-code rows
# are needed for them: PHYSICAL_KEY_TO_VK already routes them to a VK_OEM_*
# constant that appears in STANDARD_SCANCODE_TO_VK.

# aVkToBits[]: which real modifier keys set which bit. Standard 3-bit
# layout used by Microsoft's own samples: bit 0 = SHIFT, bit 1 = CTRL,
# bit 2 = ALT (KBDSHIFT/KBDCTRL/KBDALT).
VK_TO_BITS: tuple[tuple[str, str], ...] = (
    ("VK_SHIFT", "KBDSHIFT"),
    ("VK_CONTROL", "KBDCTRL"),
    ("VK_MENU", "KBDALT"),
)

# aModification[]: maps the 3-bit (CTRL, ALT, SHIFT) combination to a
# Modification Number, i.e. an index into each aVkToWchars*.wch[] array.
# Kitt only defines base (index 0) and shift (index 1) outputs. Every
# combination involving CTRL and/or ALT is marked SHFT_INVALID so Ctrl+letter
# keeps behaving like an ordinary Windows shortcut instead of emitting a
# Ukrainian letter (KITT_ARCHITECTURE.md section 7, "Safety invariants").
# Index is (CTRL<<2 | ALT<<1 | SHIFT), matching kbd.h's own example table.
MODIFICATION_NUMBERS: tuple[str, ...] = (
    "0",             # 000 <none>            -> base
    "1",             # 001 SHIFT             -> shift
    "SHFT_INVALID",  # 010 ALT
    "SHFT_INVALID",  # 011 SHIFT ALT
    "SHFT_INVALID",  # 100 CTRL
    "SHFT_INVALID",  # 101 SHIFT CTRL
    "SHFT_INVALID",  # 110 CTRL ALT
    "SHFT_INVALID",  # 111 SHIFT CTRL ALT
)

# Kitt keys are always CAPLOK: Caps Lock affects them exactly like Shift,
# matching behavior.caps_lock: letters_only in the YAML (every mapped key
# here is a letter).
KEY_ATTRIBUTES = "CAPLOK"

C_TABLE_NAME_MODIFIERS = "kitt_CharModifiers"
C_TABLE_NAME_VK_TO_BITS = "kitt_VkToBits"
C_TABLE_NAME_VSC_TO_VK = "kitt_VscToVk"
C_TABLE_NAME_VK_TO_WCHARS = "kitt_VkToWchars2"
C_TABLE_NAME_VK_TO_WCHAR_TABLE = "kitt_VkToWcharTable"
C_TABLE_NAME_DEAD_KEY = "kitt_DeadKey"
C_TABLE_NAME_KEY_NAMES = "kitt_KeyNames"
C_FUNCTION_NAME = "KbdLayerDescriptor"


@dataclass(frozen=True)
class _WcharRow:
    """One row of the VK_TO_WCHARS2 table: a single VK's base+shift output."""

    vk: str
    base: str
    shift: str
    comment: str


def _wchar_literal(ch: str | None) -> str:
    """Render a single output character as a C WCHAR literal, or WCH_NONE."""
    if ch is None:
        return "WCH_NONE"
    if len(ch) != 1:
        raise ValueError(f"expected a single Unicode scalar output, got {ch!r}")
    return f"0x{ord(ch):04X}"


def _dead_key_wchar_literal() -> str:
    return "WCH_DEAD"


def _collect_wchar_rows(spec: LayoutSpec) -> list[_WcharRow]:
    """Build one VK_TO_WCHARS2 row per normal (non-dead-key) physical key,
    plus one row per dead key's trigger VK (marked WCH_DEAD/WCH_DEAD)."""
    rows: list[_WcharRow] = []

    for physical_key in sorted(spec.keys):
        outputs: KeyOutputs = spec.keys[physical_key]
        vk = _vk_for_physical_key(physical_key)
        base = outputs.get(BASE)
        shift = outputs.get(SHIFT)
        rows.append(
            _WcharRow(
                vk=vk,
                base=_wchar_literal(base),
                shift=_wchar_literal(shift),
                comment=f"{physical_key}: base={base!r} shift={shift!r}",
            )
        )

    for dead_key_name in sorted(spec.dead_keys):
        vk = _vk_for_physical_key(dead_key_name)
        rows.append(
            _WcharRow(
                vk=vk,
                base=_dead_key_wchar_literal(),
                shift=_dead_key_wchar_literal(),
                comment=f"{dead_key_name}: dead key (WCH_DEAD)",
            )
        )

    rows.sort(key=lambda r: r.vk)
    return rows


def _c_vk_expr(vk_name: str) -> str:
    """Render a VK_* name as a C expression usable in a static initializer.

    winuser.h deliberately does NOT #define VK_A..VK_Z or VK_0..VK_9 (see
    its own comment: "VK_A - VK_Z are the same as ASCII 'A' - 'Z'"). Using
    the bare name (e.g. "VK_A") in generated C therefore fails to compile
    with C2065 "undeclared identifier" — confirmed by actually compiling
    the generated kitt_tables.c with MSVC. Every other VK_* constant (the
    function keys, VK_OEM_*, VK_SHIFT, etc.) IS #define'd in winuser.h and
    must be emitted as-is.
    """
    if len(vk_name) == 4 and vk_name.startswith("VK_") and vk_name[3].isalpha():
        return f"'{vk_name[3]}'"
    if len(vk_name) == 4 and vk_name.startswith("VK_") and vk_name[3].isdigit():
        return f"'{vk_name[3]}'"
    return vk_name


def _vk_for_physical_key(physical_key: str) -> str:
    """Resolve a YAML physical_key identifier to a VK_* C expression.

    `Y` (the dead-key trigger name used in kitt.uk-UA.yaml's `dead_keys`
    section) is a bare Latin letter identifier, not a `KeyY`-style name, so
    it is handled the same way KeyY would be.
    """
    if physical_key in PHYSICAL_KEY_TO_VK:
        return _c_vk_expr(PHYSICAL_KEY_TO_VK[physical_key])
    if len(physical_key) == 1 and physical_key.isalpha():
        return _c_vk_expr(f"VK_{physical_key.upper()}")
    raise ValueError(
        f"no known VK_* mapping for physical_key {physical_key!r}; "
        "add it to PHYSICAL_KEY_TO_VK in windows.py"
    )


def _collect_dead_key_entries(spec: LayoutSpec) -> list[tuple[str, str, str, str]]:
    """Build DEADTRANS(...) rows: (following_char_literal, accent_char_literal,
    composed_char_literal, comment).

    Windows identifies "which dead key" a DEADKEY row belongs to by the
    literal WCHAR that dead key's *base* (unshifted) row produced before it
    was marked WCH_DEAD in aVkToWchars — see kbd.h's DEADTRANS macro:
    `dwBoth = MAKELONG(ch, accent)`, where `accent` is that identifying
    character and `ch` is the character physically typed next. Kitt's dead
    key always identifies as `dead_spec.alone.base` (e.g. Y's identity is
    'й', not 'Й'), matching how a real Windows dead key is a single VK_DEAD
    entry, not one per shift state.

    For the following key, Kitt defines one combination output per modifier
    (base/shift) under each combination entry (e.g. Y+A: base='я',
    shift='Я'). The character "physically typed next" for a given shift
    state is the *following* key's own output under that same shift state,
    e.g. Shift+A after the dead key types 'А' (KeyA.shift), and Windows
    composes it against the accent to produce 'Я' (the combination's shift
    output). So each combination entry contributes one DEADTRANS row per
    modifier it defines, using the *following key's own* output as `ch`.
    """
    entries: list[tuple[str, str, str, str]] = []

    for dead_key_name in sorted(spec.dead_keys):
        dead_spec: DeadKeySpec = spec.dead_keys[dead_key_name]
        accent_char = dead_spec.alone.get(BASE)
        if accent_char is None:
            raise ValueError(
                f"dead_keys.{dead_key_name}.alone has no 'base' output; "
                "cannot identify this dead key for DEADTRANS"
            )

        for combo_key in sorted(dead_spec.combinations):
            combo: DeadKeyCombination = dead_spec.combinations[combo_key]
            following_key_outputs = spec.keys.get(combo_key)
            for modifier, composed_char in sorted(combo.by_modifier.items()):
                following_char = (
                    following_key_outputs.get(modifier)
                    if following_key_outputs is not None
                    else None
                )
                if following_char is None:
                    # The following physical key has no output of its own
                    # under this modifier (e.g. it is itself another
                    # dead-key trigger, or simply undefined) — nothing to
                    # compose against, so skip rather than guess.
                    continue
                entries.append(
                    (
                        _wchar_literal(following_char),
                        _wchar_literal(accent_char),
                        _wchar_literal(composed_char),
                        f"{dead_key_name} + {combo_key}.{modifier} "
                        f"({following_char!r}) -> {composed_char!r}",
                    )
                )

    return entries


def generate_kbdtables_source(spec: LayoutSpec) -> str:
    """Generate a complete .c source file implementing KBDTABLES for `spec`.

    The returned string is a self-contained translation unit: it includes
    <windows.h> and "kbd.h", defines every table KBDTABLES references, and
    exports `KbdLayerDescriptor()` returning a pointer to the populated
    struct, matching the standard pattern used by Microsoft's WDK keyboard
    layout samples (kbdxx.c).
    """
    lines: list[str] = []
    lines.append(GENERATED_FILE_WARNING)
    lines.append(f"// Layout: {spec.metadata.name} ({spec.metadata.id}), "
                 f"version {spec.metadata.version}")
    lines.append(f"// Language: {spec.metadata.language}")
    lines.append(f"// Description: {spec.metadata.description}")
    lines.append("")
    lines.append("#include <windows.h>")
    lines.append('#include "kbd.h"')
    lines.append("")

    lines.extend(_render_vk_to_bits())
    lines.append("")
    lines.extend(_render_modifiers())
    lines.append("")
    lines.extend(_render_vk_to_wchars(spec))
    lines.append("")
    lines.extend(_render_vk_to_wchar_table())
    lines.append("")

    wchar_rows_present = bool(spec.keys) or bool(spec.dead_keys)
    dead_key_entries = _collect_dead_key_entries(spec)
    if dead_key_entries:
        lines.extend(_render_dead_keys(dead_key_entries))
        lines.append("")

    lines.extend(_render_scancode_to_vk())
    lines.append("")
    lines.extend(_render_key_names())
    lines.append("")
    lines.extend(_render_kbdtables(has_dead_keys=bool(dead_key_entries)))
    lines.append("")
    lines.extend(_render_descriptor_function())
    lines.append("")

    _ = wchar_rows_present  # keys/dead_keys always populate at least one table
    return "\n".join(lines) + "\n"


def _render_vk_to_bits() -> list[str]:
    lines = [
        "// aVkToBits[]: real modifier keys -> modifier bitmask.",
        "// Kitt only uses SHIFT for its own letter outputs; CTRL/ALT bits are",
        "// still tracked so aModification[] can mark those combinations",
        "// SHFT_INVALID (see MODIFICATION_NUMBERS comment in windows.py).",
        f"static VK_TO_BIT {C_TABLE_NAME_VK_TO_BITS}[] = {{",
    ]
    for vk, bit in VK_TO_BITS:
        lines.append(f"    {{ {vk}, {bit} }},")
    lines.append("    { 0, 0 },")
    lines.append("};")
    return lines


def _render_modifiers() -> list[str]:
    lines = [
        "// aModification[]: (CTRL,ALT,SHIFT) bit combination -> Modification",
        "// Number (index into each VK_TO_WCHARS2.wch[]). Only base (0) and",
        "// shift (1) are defined; every state involving CTRL and/or ALT is",
        "// SHFT_INVALID so Ctrl+<letter> keeps working as a normal Windows",
        "// shortcut instead of emitting a Ukrainian letter.",
        f"static MODIFIERS {C_TABLE_NAME_MODIFIERS} = {{",
        f"    {C_TABLE_NAME_VK_TO_BITS},",
        "    7,  // wMaxModBits (CTRL|ALT|SHIFT = 0x7)",
        "    {",
    ]
    for value in MODIFICATION_NUMBERS:
        lines.append(f"        {value},")
    lines.append("    },")
    lines.append("};")
    return lines


def _render_vk_to_wchars(spec: LayoutSpec) -> list[str]:
    rows = _collect_wchar_rows(spec)
    lines = [
        "// aVkToWchars2[]: one row per Kitt-mapped VK, with 2 shift states",
        "// (index 0 = base, index 1 = shift), matching aModification[] above.",
        f"static VK_TO_WCHARS2 {C_TABLE_NAME_VK_TO_WCHARS}[] = {{",
    ]
    for row in rows:
        lines.append(
            f"    {{ {row.vk}, {KEY_ATTRIBUTES}, {{ {row.base}, {row.shift} }} }},"
            f"  // {row.comment}"
        )
    lines.append("    { 0, 0, { 0, 0 } },  // terminator")
    lines.append("};")
    return lines


def _render_vk_to_wchar_table() -> list[str]:
    lines = [
        "// aVkToWcharTable[]: groups of VK_TO_WCHARS tables by shift-state",
        "// count. Kitt only has one group (2 shift states: base, shift).",
        f"static VK_TO_WCHAR_TABLE {C_TABLE_NAME_VK_TO_WCHAR_TABLE}[] = {{",
        f"    {{ (PVK_TO_WCHARS1)(void*){C_TABLE_NAME_VK_TO_WCHARS}, "
        "2, sizeof(VK_TO_WCHARS2) },",
        "    { NULL, 0, 0 },  // terminator",
        "};",
    ]
    return lines


def _render_dead_keys(entries: list[tuple[str, str, str, str]]) -> list[str]:
    lines = [
        "// aDeadKey[]: dead-key combination -> composed character.",
        "// dwBoth = MAKELONG(following_char, accent_char): low word is the",
        "// character typed after the dead key, high word is the dead key's",
        "// own accent (\"alone\") character.",
        f"static DEADKEY {C_TABLE_NAME_DEAD_KEY}[] = {{",
    ]
    for following_lit, accent_lit, composed_lit, comment in entries:
        lines.append(
            f"    DEADTRANS({following_lit}, {accent_lit}, {composed_lit}, DKF_DEAD),"
            f"  // {comment}"
        )
    lines.append("    DEADTRANS(0, 0, 0, 0),  // terminator")
    lines.append("};")
    return lines


def _render_scancode_to_vk() -> list[str]:
    max_scancode = max(code for code, _ in STANDARD_SCANCODE_TO_VK)
    lines = [
        "// aVscToVk[]: standard PC/AT-101 scan-code -> virtual-key table.",
        "// Kitt does not remap physical key positions, only what each VK",
        "// produces, so this table matches an ordinary US/ISO layout.",
        f"static USHORT {C_TABLE_NAME_VSC_TO_VK}[] = {{",
    ]
    # pusVSCtoVK is indexed directly by scan code (Windows reads
    # pusVSCtoVK[vsc]), so index 0 must correspond to scan code 0x00, not
    # scan code 0x01 — confirmed by loading this generator's own compiled
    # DLL and reading back pusVSCtoVK, which caught an earlier off-by-one
    # here (index 0 held scan code 1's VK, shifting every entry by one).
    table = {code: vk for code, vk in STANDARD_SCANCODE_TO_VK}
    for scancode in range(0, max_scancode + 1):
        vk = table.get(scancode)
        vk_expr = _c_vk_expr(vk) if vk is not None else "0"
        lines.append(f"    /* 0x{scancode:02X} */ {vk_expr},")
    lines.append("};")
    return lines


def _render_key_names() -> list[str]:
    # Minimal key-name table: Windows falls back to defaults for anything not
    # listed, and Kitt does not rename any key, so this is intentionally
    # empty (terminator-only), matching kbd.h's documented "table" shape.
    lines = [
        "// aKeyNames[]: display names for keys shown in OS key-name UI.",
        "// Kitt does not rename any key, so this table only has the",
        "// required NULL terminator.",
        f"static VSC_LPWSTR {C_TABLE_NAME_KEY_NAMES}[] = {{",
        "    { 0, NULL },",
        "};",
    ]
    return lines


def _render_kbdtables(*, has_dead_keys: bool) -> list[str]:
    dead_key_field = f"{C_TABLE_NAME_DEAD_KEY}" if has_dead_keys else "NULL"
    lines = [
        "// Root KBDTABLES struct: ties every table above together. Returned",
        f"// by {C_FUNCTION_NAME}() below, per the standard WDK keyboard-",
        "// layout DLL export contract.",
        "static KBDTABLES kitt_KbdTables = {",
        f"    &{C_TABLE_NAME_MODIFIERS},              // pCharModifiers",
        f"    {C_TABLE_NAME_VK_TO_WCHAR_TABLE},        // pVkToWcharTable",
        f"    {dead_key_field},                        // pDeadKey",
        f"    {C_TABLE_NAME_KEY_NAMES},                // pKeyNames",
        "    NULL,                                    // pKeyNamesExt",
        "    NULL,                                    // pKeyNamesDead",
        f"    {C_TABLE_NAME_VSC_TO_VK},                // pusVSCtoVK",
        f"    (BYTE)(sizeof({C_TABLE_NAME_VSC_TO_VK}) / "
        f"sizeof({C_TABLE_NAME_VSC_TO_VK}[0])),  // bMaxVSCtoVK",
        "    NULL,                                    // pVSCtoVK_E0",
        "    NULL,                                    // pVSCtoVK_E1",
        "    0,                                       // fLocaleFlags (no AltGr)",
        "    0,                                       // nLgMax (no ligatures)",
        "    0,                                       // cbLgEntry",
        "    NULL,                                    // pLigature",
        "    0,                                       // dwType",
        "    0,                                       // dwSubType",
        "};",
    ]
    return lines


def _render_descriptor_function() -> list[str]:
    lines = [
        "// Standard WDK keyboard-layout DLL export: returns the KBDTABLES",
        "// struct describing this layout. See kbd.def/.def export file for",
        "// the corresponding EXPORTS entry.",
        f"__declspec(dllexport) PKBDTABLES WINAPI {C_FUNCTION_NAME}(VOID)",
        "{",
        "    return &kitt_KbdTables;",
        "}",
    ]
    return lines
