/*
 * GENERATED FILE - DO NOT EDIT.
 *
 * This file was generated by `python -m kittgen generate` from
 * layout/kitt.uk-UA.yaml, overlaid on a dump of the real Windows-shipped
 * Turkish Q driver (kbdtuq_reference.json). Edit the YAML file and
 * regenerate instead of hand-editing this file (KITT_ARCHITECTURE.md
 * section 32: "generated tables clearly marked as generated").
 */

// Layout: Kitt (kitt-uk-ua), version 0.1.0
// Language: uk-UA
// Description: Ukrainian mnemonic keyboard layout for Turkish Q physical keyboards
//
// Base tables: the real Windows-shipped Turkish Q driver (KBDTUQ.DLL),
// copied verbatim. Kitt overrides base/Shift on 29 virtual keys;
// every other key and shift state (AltGr, Ctrl+Alt, dead-key accents,
// the keypad, navigation keys) keeps its Turkish Q behavior.

#include <windows.h>
#include "kbd.h"

// aVkToBits[]: real modifier keys -> modifier bitmask, copied from
// the Turkish Q driver. bit 0 = SHIFT, bit 1 = CTRL, bit 2 = ALT.
static VK_TO_BIT kitt_VkToBits[] = {
    { VK_SHIFT, KBDSHIFT },
    { VK_CONTROL, KBDCTRL },
    { VK_MENU, KBDALT },
    { 0, 0 },
};

// aModification[]: (CTRL,ALT,SHIFT) bit combination -> Modification
// Number (index into each VK_TO_WCHARS*.wch[]). Copied verbatim from
// the Turkish Q driver, which already satisfies Kitt's safety
// invariant (KITT_ARCHITECTURE.md section 7): the pure-CTRL and
// SHIFT+CTRL states are SHFT_INVALID, so Ctrl+<letter> stays an
// ordinary Windows shortcut instead of emitting a Ukrainian letter.
static MODIFIERS kitt_CharModifiers = {
    kitt_VkToBits,
    7,  // wMaxModBits
    {
        0,  // 000 <none>
        1,  // 001 SHIFT
        3,  // 010 ALT
        4,  // 011 SHIFT ALT
        SHFT_INVALID,  // 100 CTRL
        SHFT_INVALID,  // 101 SHIFT CTRL
        2,  // 110 CTRL ALT
        5,  // 111 SHIFT CTRL ALT
    },
};

// aVkToWchars3[]: every VK with 3 shift states, from the Turkish Q driver, with Kitt's
// base/Shift overrides applied. Columns follow aModification[]:
//   [0] base  [1] SHIFT  [2] CTRL+ALT  [3] ALTGR  [4] SHIFT+ALTGR  [5] SHIFT+CTRL+ALT
static VK_TO_WCHARS3 kitt_VkToWchars3[] = {
    { 0xC0, 0, { 0x0022, 0x00E9, 0x003C } },
    { '1', 0, { 0x0031, 0x0021, 0x003E } },
    { '3', 0, { 0x0033, WCH_DEAD, 0x0023 } },
    { 0xFF, 0, { WCH_NONE, 0x005E, WCH_NONE } },  // dead chars for the row above
    { '4', 0, { 0x0034, 0x002B, 0x0024 } },
    { '5', 0, { 0x0035, 0x0025, 0x00BD } },
    { '7', 0, { 0x0037, 0x002F, 0x007B } },
    { '8', 0, { 0x0038, 0x0028, 0x005B } },
    { '9', 0, { 0x0039, 0x0029, 0x005D } },
    { '0', 0, { 0x0030, 0x003D, 0x007D } },
    { 0xDF, 0, { 0x002A, 0x003F, 0x005C } },
    { 'Q', CAPLOK, { 0x0449, 0x0429, 0x0040 } },  // KeyQ: base='щ' shift='Щ'
    { 'E', CAPLOK, { 0x0435, 0x0415, 0x20AC } },  // KeyE: base='е' shift='Е'
    { 'T', CAPLOK, { 0x0442, 0x0422, 0x20BA } },  // KeyT: base='т' shift='Т'
    { 'S', CAPLOK, { 0x0441, 0x0421, 0x00DF } },  // KeyS: base='с' shift='С'
    { VK_OEM_1, CAPLOK, { 0x0448, 0x0428, WCH_DEAD } },  // KeySCedilla: base='ш' shift='Ш'
    { 0xFF, 0, { WCH_NONE, WCH_NONE, 0x00B4 } },  // dead chars for the row above
    { 0, 0, { 0, 0, 0 } },  // terminator
};

// aVkToWchars4[]: every VK with 4 shift states, from the Turkish Q driver, with Kitt's
// base/Shift overrides applied. Columns follow aModification[]:
//   [0] base  [1] SHIFT  [2] CTRL+ALT  [3] ALTGR  [4] SHIFT+ALTGR  [5] SHIFT+CTRL+ALT
static VK_TO_WCHARS4 kitt_VkToWchars4[] = {
    { VK_OEM_4, CAPLOK, { 0x0433, 0x0413, WCH_DEAD, 0x001B } },  // KeyGBreve: base='г' shift='Г'
    { 0xFF, 0, { WCH_NONE, WCH_NONE, 0x00A8, WCH_NONE } },  // dead chars for the row above
    { 0xDD, CAPLOK, { 0x00FC, 0x00DC, WCH_DEAD, 0x001D } },
    { 0xFF, 0, { WCH_NONE, WCH_NONE, 0x007E, WCH_NONE } },  // dead chars for the row above
    { 0xBC, 0, { 0x002C, 0x003B, WCH_DEAD, 0x001C } },
    { 0xFF, 0, { WCH_NONE, WCH_NONE, 0x0060, WCH_NONE } },  // dead chars for the row above
    { 0xE2, 0, { 0x003C, 0x003E, 0x007C, 0x001C } },
    { 0x08, 0, { 0x0008, 0x0008, WCH_NONE, 0x007F } },
    { 0x1B, 0, { 0x001B, 0x001B, WCH_NONE, 0x001B } },
    { 0x0D, 0, { 0x000D, 0x000D, WCH_NONE, 0x000A } },
    { 0x20, 0, { 0x0020, 0x0020, WCH_NONE, 0x0020 } },
    { 0x03, 0, { 0x0003, 0x0003, WCH_NONE, 0x0003 } },
    { 0, 0, { 0, 0, 0, 0 } },  // terminator
};

// aVkToWchars5[]: every VK with 5 shift states, from the Turkish Q driver, with Kitt's
// base/Shift overrides applied. Columns follow aModification[]:
//   [0] base  [1] SHIFT  [2] CTRL+ALT  [3] ALTGR  [4] SHIFT+ALTGR  [5] SHIFT+CTRL+ALT
static VK_TO_WCHARS5 kitt_VkToWchars5[] = {
    { '2', 0, { 0x0032, 0x0027, 0x00A3, WCH_NONE, 0x0000 } },
    { '6', 0, { 0x0036, 0x0026, WCH_NONE, WCH_NONE, 0x001E } },
    { 0xBD, 0, { 0x002D, 0x005F, 0x007C, WCH_NONE, 0x001F } },
    { 0, 0, { 0, 0, 0, 0, 0 } },  // terminator
};

// aVkToWchars6[]: every VK with 6 shift states, from the Turkish Q driver, with Kitt's
// base/Shift overrides applied. Columns follow aModification[]:
//   [0] base  [1] SHIFT  [2] CTRL+ALT  [3] ALTGR  [4] SHIFT+ALTGR  [5] SHIFT+CTRL+ALT
static VK_TO_WCHARS6 kitt_VkToWchars6[] = {
    { 'I', CAPLOK | CAPLOKALTGR, { 0x0438, 0x0418, 0x0069, WCH_NONE, WCH_NONE, 0x0130 } },  // KeyI: base='и' shift='И'
    { 'A', CAPLOK | CAPLOKALTGR, { 0x0430, 0x0410, 0x00E6, WCH_NONE, WCH_NONE, 0x00C6 } },  // KeyA: base='а' shift='А'
    { 0, 0, { 0, 0, 0, 0, 0, 0 } },  // terminator
};

// aVkToWchars2[]: every VK with 2 shift states, from the Turkish Q driver, with Kitt's
// base/Shift overrides applied. Columns follow aModification[]:
//   [0] base  [1] SHIFT  [2] CTRL+ALT  [3] ALTGR  [4] SHIFT+ALTGR  [5] SHIFT+CTRL+ALT
static VK_TO_WCHARS2 kitt_VkToWchars2[] = {
    { 'W', CAPLOK, { 0x0077, 0x0057 } },
    { 'R', CAPLOK, { 0x0440, 0x0420 } },  // KeyR: base='р' shift='Р'
    { 'Y', CAPLOK, { WCH_DEAD, WCH_DEAD } },  // Y: dead key, base identity='й' shift identity='Й'
    { 0xFF, 0, { 0x0439, 0x0419 } },  // dead chars for the row above
    { 'U', CAPLOK, { 0x0443, 0x0423 } },  // KeyU: base='у' shift='У'
    { 'O', CAPLOK, { 0x043E, 0x041E } },  // KeyO: base='о' shift='О'
    { 'P', CAPLOK, { 0x043F, 0x041F } },  // KeyP: base='п' shift='П'
    { 'D', CAPLOK, { 0x0434, 0x0414 } },  // KeyD: base='д' shift='Д'
    { 'F', CAPLOK, { 0x0444, 0x0424 } },  // KeyF: base='ф' shift='Ф'
    { 'G', CAPLOK, { 0x0491, 0x0490 } },  // KeyG: base='ґ' shift='Ґ'
    { 'H', CAPLOK, { 0x0445, 0x0425 } },  // KeyH: base='х' shift='Х'
    { 'J', CAPLOK, { 0x0436, 0x0416 } },  // KeyJ: base='ж' shift='Ж'
    { 'K', CAPLOK, { 0x043A, 0x041A } },  // KeyK: base='к' shift='К'
    { 'L', CAPLOK, { 0x043B, 0x041B } },  // KeyL: base='л' shift='Л'
    { VK_OEM_7, CAPLOK, { 0x0456, 0x0406 } },  // KeyISlash: base='і' shift='І'
    { 'Z', CAPLOK, { 0x0437, 0x0417 } },  // KeyZ: base='з' shift='З'
    { 'X', CAPLOK, { 0x044C, 0x042C } },  // KeyX: base='ь' shift='Ь'
    { 'C', CAPLOK, { 0x0446, 0x0426 } },  // KeyC: base='ц' shift='Ц'
    { 'V', CAPLOK, { 0x0432, 0x0412 } },  // KeyV: base='в' shift='В'
    { 'B', CAPLOK, { 0x0431, 0x0411 } },  // KeyB: base='б' shift='Б'
    { 'N', CAPLOK, { 0x043D, 0x041D } },  // KeyN: base='н' shift='Н'
    { 'M', CAPLOK, { 0x043C, 0x041C } },  // KeyM: base='м' shift='М'
    { 0xBF, CAPLOK, { 0x00F6, 0x00D6 } },
    { VK_OEM_5, CAPLOK, { 0x0447, 0x0427 } },  // KeyCCedilla: base='ч' shift='Ч'
    { 0xBE, 0, { 0x002E, 0x003A } },
    { 0x6E, 0, { 0x002C, 0x002C } },
    { 0x09, 0, { 0x0009, 0x0009 } },
    { 0x6B, 0, { 0x002B, 0x002B } },
    { 0x6F, 0, { 0x002F, 0x002F } },
    { 0x6A, 0, { 0x002A, 0x002A } },
    { 0x6D, 0, { 0x002D, 0x002D } },
    { 0, 0, { 0, 0 } },  // terminator
};

// aVkToWchars1[]: every VK with 1 shift state, from the Turkish Q driver, with Kitt's
// base/Shift overrides applied. Columns follow aModification[]:
//   [0] base  [1] SHIFT  [2] CTRL+ALT  [3] ALTGR  [4] SHIFT+ALTGR  [5] SHIFT+CTRL+ALT
static VK_TO_WCHARS1 kitt_VkToWchars1[] = {
    { 0x60, 0, { 0x0030 } },
    { 0x61, 0, { 0x0031 } },
    { 0x62, 0, { 0x0032 } },
    { 0x63, 0, { 0x0033 } },
    { 0x64, 0, { 0x0034 } },
    { 0x65, 0, { 0x0035 } },
    { 0x66, 0, { 0x0036 } },
    { 0x67, 0, { 0x0037 } },
    { 0x68, 0, { 0x0038 } },
    { 0x69, 0, { 0x0039 } },
    { 0, 0, { 0 } },  // terminator
};

// aVkToWcharTable[]: every VK_TO_WCHARS group above, tagged with its
// shift-state count so Windows knows how wide each row's wch[] is.
static VK_TO_WCHAR_TABLE kitt_VkToWcharTable[] = {
    { (PVK_TO_WCHARS1)(void*)kitt_VkToWchars3, 3, sizeof(VK_TO_WCHARS3) },
    { (PVK_TO_WCHARS1)(void*)kitt_VkToWchars4, 4, sizeof(VK_TO_WCHARS4) },
    { (PVK_TO_WCHARS1)(void*)kitt_VkToWchars5, 5, sizeof(VK_TO_WCHARS5) },
    { (PVK_TO_WCHARS1)(void*)kitt_VkToWchars6, 6, sizeof(VK_TO_WCHARS6) },
    { (PVK_TO_WCHARS1)(void*)kitt_VkToWchars2, 2, sizeof(VK_TO_WCHARS2) },
    { (PVK_TO_WCHARS1)(void*)kitt_VkToWchars1, 1, sizeof(VK_TO_WCHARS1) },
    { NULL, 0, 0 },  // terminator
};

// aDeadKey[]: dead-key combination -> composed character.
// dwBoth = MAKELONG(following_char, accent_char): low word is the
// character typed after the dead key, high word is the dead key's
// own identity character (from its DEADCHARS row above).
// The Turkish Q accents (circumflex, acute, diaeresis, grave, tilde)
// are preserved as-is; Kitt's own Y combinations are appended.
static DEADKEY kitt_DeadKey[] = {
    DEADTRANS(0x0061, 0x005E, 0x00E2, 0x0000),  // Turkish Q: '^' + 'a' -> 'â'
    DEADTRANS(0x0065, 0x005E, 0x00EA, 0x0000),  // Turkish Q: '^' + 'e' -> 'ê'
    DEADTRANS(0x0069, 0x005E, 0x00EE, 0x0000),  // Turkish Q: '^' + 'i' -> 'î'
    DEADTRANS(0x0131, 0x005E, 0x00EE, 0x0000),  // Turkish Q: '^' + 'ı' -> 'î'
    DEADTRANS(0x006F, 0x005E, 0x00F4, 0x0000),  // Turkish Q: '^' + 'o' -> 'ô'
    DEADTRANS(0x0075, 0x005E, 0x00FB, 0x0000),  // Turkish Q: '^' + 'u' -> 'û'
    DEADTRANS(0x0041, 0x005E, 0x00C2, 0x0000),  // Turkish Q: '^' + 'A' -> 'Â'
    DEADTRANS(0x0045, 0x005E, 0x00CA, 0x0000),  // Turkish Q: '^' + 'E' -> 'Ê'
    DEADTRANS(0x0049, 0x005E, 0x00CE, 0x0000),  // Turkish Q: '^' + 'I' -> 'Î'
    DEADTRANS(0x0130, 0x005E, 0x00CE, 0x0000),  // Turkish Q: '^' + 'İ' -> 'Î'
    DEADTRANS(0x004F, 0x005E, 0x00D4, 0x0000),  // Turkish Q: '^' + 'O' -> 'Ô'
    DEADTRANS(0x0055, 0x005E, 0x00DB, 0x0000),  // Turkish Q: '^' + 'U' -> 'Û'
    DEADTRANS(0x0020, 0x005E, 0x005E, 0x0000),  // Turkish Q: '^' + ' ' -> '^'
    DEADTRANS(0x0061, 0x00B4, 0x00E1, 0x0000),  // Turkish Q: '´' + 'a' -> 'á'
    DEADTRANS(0x0065, 0x00B4, 0x00E9, 0x0000),  // Turkish Q: '´' + 'e' -> 'é'
    DEADTRANS(0x0069, 0x00B4, 0x00ED, 0x0000),  // Turkish Q: '´' + 'i' -> 'í'
    DEADTRANS(0x0131, 0x00B4, 0x00ED, 0x0000),  // Turkish Q: '´' + 'ı' -> 'í'
    DEADTRANS(0x006F, 0x00B4, 0x00F3, 0x0000),  // Turkish Q: '´' + 'o' -> 'ó'
    DEADTRANS(0x0075, 0x00B4, 0x00FA, 0x0000),  // Turkish Q: '´' + 'u' -> 'ú'
    DEADTRANS(0x0041, 0x00B4, 0x00C1, 0x0000),  // Turkish Q: '´' + 'A' -> 'Á'
    DEADTRANS(0x0045, 0x00B4, 0x00C9, 0x0000),  // Turkish Q: '´' + 'E' -> 'É'
    DEADTRANS(0x0049, 0x00B4, 0x00CD, 0x0000),  // Turkish Q: '´' + 'I' -> 'Í'
    DEADTRANS(0x0130, 0x00B4, 0x00CD, 0x0000),  // Turkish Q: '´' + 'İ' -> 'Í'
    DEADTRANS(0x004F, 0x00B4, 0x00D3, 0x0000),  // Turkish Q: '´' + 'O' -> 'Ó'
    DEADTRANS(0x0055, 0x00B4, 0x00DA, 0x0000),  // Turkish Q: '´' + 'U' -> 'Ú'
    DEADTRANS(0x0020, 0x00B4, 0x00B4, 0x0000),  // Turkish Q: '´' + ' ' -> '´'
    DEADTRANS(0x0061, 0x00A8, 0x00E4, 0x0000),  // Turkish Q: '¨' + 'a' -> 'ä'
    DEADTRANS(0x0065, 0x00A8, 0x00EB, 0x0000),  // Turkish Q: '¨' + 'e' -> 'ë'
    DEADTRANS(0x0069, 0x00A8, 0x00EF, 0x0000),  // Turkish Q: '¨' + 'i' -> 'ï'
    DEADTRANS(0x0131, 0x00A8, 0x00EF, 0x0000),  // Turkish Q: '¨' + 'ı' -> 'ï'
    DEADTRANS(0x006F, 0x00A8, 0x00F6, 0x0000),  // Turkish Q: '¨' + 'o' -> 'ö'
    DEADTRANS(0x0075, 0x00A8, 0x00FC, 0x0000),  // Turkish Q: '¨' + 'u' -> 'ü'
    DEADTRANS(0x0041, 0x00A8, 0x00C4, 0x0000),  // Turkish Q: '¨' + 'A' -> 'Ä'
    DEADTRANS(0x0045, 0x00A8, 0x00CB, 0x0000),  // Turkish Q: '¨' + 'E' -> 'Ë'
    DEADTRANS(0x0049, 0x00A8, 0x00CF, 0x0000),  // Turkish Q: '¨' + 'I' -> 'Ï'
    DEADTRANS(0x0130, 0x00A8, 0x00CF, 0x0000),  // Turkish Q: '¨' + 'İ' -> 'Ï'
    DEADTRANS(0x004F, 0x00A8, 0x00D6, 0x0000),  // Turkish Q: '¨' + 'O' -> 'Ö'
    DEADTRANS(0x0055, 0x00A8, 0x00DC, 0x0000),  // Turkish Q: '¨' + 'U' -> 'Ü'
    DEADTRANS(0x0020, 0x00A8, 0x00A8, 0x0000),  // Turkish Q: '¨' + ' ' -> '¨'
    DEADTRANS(0x0061, 0x0060, 0x00E0, 0x0000),  // Turkish Q: '`' + 'a' -> 'à'
    DEADTRANS(0x0065, 0x0060, 0x00E8, 0x0000),  // Turkish Q: '`' + 'e' -> 'è'
    DEADTRANS(0x0069, 0x0060, 0x00EC, 0x0000),  // Turkish Q: '`' + 'i' -> 'ì'
    DEADTRANS(0x0131, 0x0060, 0x00EC, 0x0000),  // Turkish Q: '`' + 'ı' -> 'ì'
    DEADTRANS(0x006F, 0x0060, 0x00F2, 0x0000),  // Turkish Q: '`' + 'o' -> 'ò'
    DEADTRANS(0x0075, 0x0060, 0x00F9, 0x0000),  // Turkish Q: '`' + 'u' -> 'ù'
    DEADTRANS(0x0041, 0x0060, 0x00C0, 0x0000),  // Turkish Q: '`' + 'A' -> 'À'
    DEADTRANS(0x0045, 0x0060, 0x00C8, 0x0000),  // Turkish Q: '`' + 'E' -> 'È'
    DEADTRANS(0x0049, 0x0060, 0x00CC, 0x0000),  // Turkish Q: '`' + 'I' -> 'Ì'
    DEADTRANS(0x0130, 0x0060, 0x00CC, 0x0000),  // Turkish Q: '`' + 'İ' -> 'Ì'
    DEADTRANS(0x004F, 0x0060, 0x00D2, 0x0000),  // Turkish Q: '`' + 'O' -> 'Ò'
    DEADTRANS(0x0055, 0x0060, 0x00D9, 0x0000),  // Turkish Q: '`' + 'U' -> 'Ù'
    DEADTRANS(0x0020, 0x0060, 0x0060, 0x0000),  // Turkish Q: '`' + ' ' -> '`'
    DEADTRANS(0x0061, 0x007E, 0x00E3, 0x0000),  // Turkish Q: '~' + 'a' -> 'ã'
    DEADTRANS(0x006F, 0x007E, 0x00F5, 0x0000),  // Turkish Q: '~' + 'o' -> 'õ'
    DEADTRANS(0x006E, 0x007E, 0x00F1, 0x0000),  // Turkish Q: '~' + 'n' -> 'ñ'
    DEADTRANS(0x0041, 0x007E, 0x00C3, 0x0000),  // Turkish Q: '~' + 'A' -> 'Ã'
    DEADTRANS(0x004F, 0x007E, 0x00D5, 0x0000),  // Turkish Q: '~' + 'O' -> 'Õ'
    DEADTRANS(0x004E, 0x007E, 0x00D1, 0x0000),  // Turkish Q: '~' + 'N' -> 'Ñ'
    DEADTRANS(0x0020, 0x007E, 0x007E, 0x0000),  // Turkish Q: '~' + ' ' -> '~'
    DEADTRANS(0x0430, 0x0439, 0x044F, DKF_DEAD),  // Kitt: Y + KeyA.base ('а') -> 'я'
    DEADTRANS(0x0410, 0x0419, 0x042F, DKF_DEAD),  // Kitt: Y + KeyA.shift ('А') -> 'Я'
    DEADTRANS(0x0435, 0x0439, 0x0454, DKF_DEAD),  // Kitt: Y + KeyE.base ('е') -> 'є'
    DEADTRANS(0x0415, 0x0419, 0x0404, DKF_DEAD),  // Kitt: Y + KeyE.shift ('Е') -> 'Є'
    DEADTRANS(0x0456, 0x0439, 0x0457, DKF_DEAD),  // Kitt: Y + KeyISlash.base ('і') -> 'ї'
    DEADTRANS(0x0406, 0x0419, 0x0407, DKF_DEAD),  // Kitt: Y + KeyISlash.shift ('І') -> 'Ї'
    DEADTRANS(0x0443, 0x0439, 0x044E, DKF_DEAD),  // Kitt: Y + KeyU.base ('у') -> 'ю'
    DEADTRANS(0x0423, 0x0419, 0x042E, DKF_DEAD),  // Kitt: Y + KeyU.shift ('У') -> 'Ю'
    DEADTRANS(0, 0, 0, 0),  // terminator
};

// aVscToVk[]: scan-code -> virtual-key table, copied from the Turkish
// Q driver. Kitt does not remap physical key positions, only what
// each VK produces, so this is the Turkish Q ISO (105-key) table
// unchanged.
static USHORT kitt_VscToVk[] = {
    /* 0x00 */ 0,
    /* 0x01 */ 0x1B,
    /* 0x02 */ '1',
    /* 0x03 */ '2',
    /* 0x04 */ '3',
    /* 0x05 */ '4',
    /* 0x06 */ '5',
    /* 0x07 */ '6',
    /* 0x08 */ '7',
    /* 0x09 */ '8',
    /* 0x0A */ '9',
    /* 0x0B */ '0',
    /* 0x0C */ 0xDF,
    /* 0x0D */ 0xBD,
    /* 0x0E */ 0x08,
    /* 0x0F */ 0x09,
    /* 0x10 */ 'Q',
    /* 0x11 */ 'W',
    /* 0x12 */ 'E',
    /* 0x13 */ 'R',
    /* 0x14 */ 'T',
    /* 0x15 */ 'Y',
    /* 0x16 */ 'U',
    /* 0x17 */ 'I',
    /* 0x18 */ 'O',
    /* 0x19 */ 'P',
    /* 0x1A */ 0xDB,
    /* 0x1B */ 0xDD,
    /* 0x1C */ 0x0D,
    /* 0x1D */ 0xA2,
    /* 0x1E */ 'A',
    /* 0x1F */ 'S',
    /* 0x20 */ 'D',
    /* 0x21 */ 'F',
    /* 0x22 */ 'G',
    /* 0x23 */ 'H',
    /* 0x24 */ 'J',
    /* 0x25 */ 'K',
    /* 0x26 */ 'L',
    /* 0x27 */ 0xBA,
    /* 0x28 */ 0xDE,
    /* 0x29 */ 0xC0,
    /* 0x2A */ 0xA0,
    /* 0x2B */ 0xBC,
    /* 0x2C */ 'Z',
    /* 0x2D */ 'X',
    /* 0x2E */ 'C',
    /* 0x2F */ 'V',
    /* 0x30 */ 'B',
    /* 0x31 */ 'N',
    /* 0x32 */ 'M',
    /* 0x33 */ 0xBF,
    /* 0x34 */ 0xDC,
    /* 0x35 */ 0xBE,
    /* 0x36 */ 0xA1,
    /* 0x37 */ 0x6A,
    /* 0x38 */ 0xA4,
    /* 0x39 */ 0x20,
    /* 0x3A */ 0x14,
    /* 0x3B */ 0x70,
    /* 0x3C */ 0x71,
    /* 0x3D */ 0x72,
    /* 0x3E */ 0x73,
    /* 0x3F */ 0x74,
    /* 0x40 */ 0x75,
    /* 0x41 */ 0x76,
    /* 0x42 */ 0x77,
    /* 0x43 */ 0x78,
    /* 0x44 */ 0x79,
    /* 0x45 */ 0x90,
    /* 0x46 */ 0x91,
    /* 0x47 */ 0x24,
    /* 0x48 */ 0x26,
    /* 0x49 */ 0x21,
    /* 0x4A */ 0x6D,
    /* 0x4B */ 0x25,
    /* 0x4C */ 0x0C,
    /* 0x4D */ 0x27,
    /* 0x4E */ 0x6B,
    /* 0x4F */ 0x23,
    /* 0x50 */ 0x28,
    /* 0x51 */ 0x22,
    /* 0x52 */ 0x2D,
    /* 0x53 */ 0x2E,
    /* 0x54 */ 0x2C,
    /* 0x55 */ 0,
    /* 0x56 */ 0xE2,
    /* 0x57 */ 0x7A,
    /* 0x58 */ 0x7B,
    /* 0x59 */ 0x0C,
    /* 0x5A */ 0xEE,
    /* 0x5B */ 0xF1,
    /* 0x5C */ 0xEA,
    /* 0x5D */ 0xF9,
    /* 0x5E */ 0xF5,
    /* 0x5F */ 0xF3,
    /* 0x60 */ 0,
    /* 0x61 */ 0,
    /* 0x62 */ 0xFB,
    /* 0x63 */ 0x2F,
    /* 0x64 */ 0x7C,
    /* 0x65 */ 0x7D,
    /* 0x66 */ 0x7E,
    /* 0x67 */ 0x7F,
    /* 0x68 */ 0x80,
    /* 0x69 */ 0x81,
    /* 0x6A */ 0x82,
    /* 0x6B */ 0x83,
    /* 0x6C */ 0x84,
    /* 0x6D */ 0x85,
    /* 0x6E */ 0x86,
    /* 0x6F */ 0xED,
    /* 0x70 */ 0,
    /* 0x71 */ 0xE9,
    /* 0x72 */ 0,
    /* 0x73 */ 0xC1,
    /* 0x74 */ 0,
    /* 0x75 */ 0,
    /* 0x76 */ 0x87,
    /* 0x77 */ 0,
    /* 0x78 */ 0,
    /* 0x79 */ 0,
    /* 0x7A */ 0,
    /* 0x7B */ 0xEB,
    /* 0x7C */ 0x09,
    /* 0x7D */ 0,
    /* 0x7E */ 0xC2,
};

// aVscToVk_E0[]: 0xE0-prefixed scan codes (arrow keys, Insert/Delete/Home/End/PageUp/PageDown, right Ctrl/Alt, numpad Enter/Divide, media keys). Copied from the Turkish Q driver. Leaving this table empty makes every extended key stop working while Kitt is active — confirmed on a real machine.
static VSC_VK kitt_VscToVk_E0[] = {
    { 0x10, 0xB1 },
    { 0x19, 0xB0 },
    { 0x1D, 0xA3 },
    { 0x20, 0xAD },
    { 0x21, 0xB7 },
    { 0x22, 0xB3 },
    { 0x24, 0xB2 },
    { 0x2E, 0xAE },
    { 0x30, 0xAF },
    { 0x32, 0xAC },
    { 0x35, 0x6F },
    { 0x37, 0x2C },
    { 0x38, 0xA5 },
    { 0x47, 0x24 },
    { 0x48, 0x26 },
    { 0x49, 0x21 },
    { 0x4B, 0x25 },
    { 0x4D, 0x27 },
    { 0x4F, 0x23 },
    { 0x50, 0x28 },
    { 0x51, 0x22 },
    { 0x52, 0x2D },
    { 0x53, 0x2E },
    { 0x5B, 0x5B },
    { 0x5C, 0x5C },
    { 0x5D, 0x5D },
    { 0x5F, 0x5F },
    { 0x65, 0xAA },
    { 0x66, 0xAB },
    { 0x67, 0xA8 },
    { 0x68, 0xA9 },
    { 0x69, 0xA7 },
    { 0x6A, 0xA6 },
    { 0x6B, 0xB6 },
    { 0x6C, 0xB4 },
    { 0x6D, 0xB5 },
    { 0x1C, 0x0D },
    { 0x46, 0x03 },
    { 0, 0 },  // terminator
};

// aVscToVk_E1[]: 0xE1-prefixed scan codes (Pause/Break).
static VSC_VK kitt_VscToVk_E1[] = {
    { 0x1D, 0x13 },
    { 0, 0 },  // terminator
};

// aKeyNames[]: display names for keys shown in OS key-name UI.
// Kitt does not rename any key, so this table only has the
// required NULL terminator.
static VSC_LPWSTR kitt_KeyNames[] = {
    { 0, NULL },
};

// Root KBDTABLES struct: ties every table above together. Returned
// by KbdLayerDescriptor() below, per the standard WDK keyboard-
// layout DLL export contract.
static KBDTABLES kitt_KbdTables = {
    &kitt_CharModifiers,              // pCharModifiers
    kitt_VkToWcharTable,        // pVkToWcharTable
    kitt_DeadKey,                        // pDeadKey
    kitt_KeyNames,                // pKeyNames
    NULL,                                    // pKeyNamesExt
    NULL,                                    // pKeyNamesDead
    kitt_VscToVk,                // pusVSCtoVK
    (BYTE)(sizeof(kitt_VscToVk) / sizeof(kitt_VscToVk[0])),  // bMaxVSCtoVK
    kitt_VscToVk_E0,             // pVSCtoVK_E0
    kitt_VscToVk_E1,             // pVSCtoVK_E1
    MAKELONG(KLLF_ALTGR, KBD_VERSION),         // fLocaleFlags
    0,                                       // nLgMax (no ligatures)
    0,                                       // cbLgEntry
    NULL,                                    // pLigature
    0,                                       // dwType
    0,                                       // dwSubType
};

// Standard WDK keyboard-layout DLL export: returns the KBDTABLES
// struct describing this layout. See kbd.def/.def export file for
// the corresponding EXPORTS entry.
__declspec(dllexport) PKBDTABLES WINAPI KbdLayerDescriptor(VOID)
{
    return &kitt_KbdTables;
}


