/*
 * GENERATED FILE - DO NOT EDIT.
 *
 * This file was generated by `python -m kittgen generate` from
 * layout/kitt.uk-UA.yaml. Edit that YAML file and regenerate instead of
 * hand-editing this file (KITT_ARCHITECTURE.md section 32: "generated
 * tables clearly marked as generated").
 */

// Layout: Kitt (kitt-uk-ua), version 0.1.0
// Language: uk-UA
// Description: Ukrainian mnemonic keyboard layout for Turkish Q physical keyboards

#include <windows.h>
#include "kbd.h"

// aVkToBits[]: real modifier keys -> modifier bitmask.
// Kitt only uses SHIFT for its own letter outputs; CTRL/ALT bits are
// still tracked so aModification[] can mark those combinations
// SHFT_INVALID (see MODIFICATION_NUMBERS comment in windows.py).
static VK_TO_BIT kitt_VkToBits[] = {
    { VK_SHIFT, KBDSHIFT },
    { VK_CONTROL, KBDCTRL },
    { VK_MENU, KBDALT },
    { 0, 0 },
};

// aModification[]: (CTRL,ALT,SHIFT) bit combination -> Modification
// Number (index into each VK_TO_WCHARS2.wch[]). Only base (0) and
// shift (1) are defined; every state involving CTRL and/or ALT is
// SHFT_INVALID so Ctrl+<letter> keeps working as a normal Windows
// shortcut instead of emitting a Ukrainian letter.
static MODIFIERS kitt_CharModifiers = {
    kitt_VkToBits,
    7,  // wMaxModBits (CTRL|ALT|SHIFT = 0x7)
    {
        0,
        1,
        SHFT_INVALID,
        SHFT_INVALID,
        SHFT_INVALID,
        SHFT_INVALID,
        SHFT_INVALID,
        SHFT_INVALID,
    },
};

// aVkToWchars2[]: one row per Kitt-mapped VK, with 2 shift states
// (index 0 = base, index 1 = shift), matching aModification[] above.
static VK_TO_WCHARS2 kitt_VkToWchars2[] = {
    { 'A', CAPLOK, { 0x0430, 0x0410 } },  // KeyA: base='а' shift='А'
    { 'B', CAPLOK, { 0x0431, 0x0411 } },  // KeyB: base='б' shift='Б'
    { 'C', CAPLOK, { 0x0446, 0x0426 } },  // KeyC: base='ц' shift='Ц'
    { 'D', CAPLOK, { 0x0434, 0x0414 } },  // KeyD: base='д' shift='Д'
    { 'E', CAPLOK, { 0x0435, 0x0415 } },  // KeyE: base='е' shift='Е'
    { 'F', CAPLOK, { 0x0444, 0x0424 } },  // KeyF: base='ф' shift='Ф'
    { 'G', CAPLOK, { 0x0491, 0x0490 } },  // KeyG: base='ґ' shift='Ґ'
    { 'H', CAPLOK, { 0x0445, 0x0425 } },  // KeyH: base='х' shift='Х'
    { 'I', CAPLOK, { 0x0438, 0x0418 } },  // KeyI: base='и' shift='И'
    { 'J', CAPLOK, { 0x0436, 0x0416 } },  // KeyJ: base='ж' shift='Ж'
    { 'K', CAPLOK, { 0x043A, 0x041A } },  // KeyK: base='к' shift='К'
    { 'L', CAPLOK, { 0x043B, 0x041B } },  // KeyL: base='л' shift='Л'
    { 'M', CAPLOK, { 0x043C, 0x041C } },  // KeyM: base='м' shift='М'
    { 'N', CAPLOK, { 0x043D, 0x041D } },  // KeyN: base='н' shift='Н'
    { 'O', CAPLOK, { 0x043E, 0x041E } },  // KeyO: base='о' shift='О'
    { 'P', CAPLOK, { 0x043F, 0x041F } },  // KeyP: base='п' shift='П'
    { 'Q', CAPLOK, { 0x0449, 0x0429 } },  // KeyQ: base='щ' shift='Щ'
    { 'R', CAPLOK, { 0x0440, 0x0420 } },  // KeyR: base='р' shift='Р'
    { 'S', CAPLOK, { 0x0441, 0x0421 } },  // KeyS: base='с' shift='С'
    { 'T', CAPLOK, { 0x0442, 0x0422 } },  // KeyT: base='т' shift='Т'
    { 'U', CAPLOK, { 0x0443, 0x0423 } },  // KeyU: base='у' shift='У'
    { 'V', CAPLOK, { 0x0432, 0x0412 } },  // KeyV: base='в' shift='В'
    { 'X', CAPLOK, { 0x044C, 0x042C } },  // KeyX: base='ь' shift='Ь'
    { 'Y', CAPLOK, { WCH_DEAD, WCH_DEAD } },  // Y: dead key (WCH_DEAD)
    { 'Z', CAPLOK, { 0x0437, 0x0417 } },  // KeyZ: base='з' shift='З'
    { VK_OEM_1, CAPLOK, { 0x0448, 0x0428 } },  // KeySCedilla: base='ш' shift='Ш'
    { VK_OEM_4, CAPLOK, { 0x0433, 0x0413 } },  // KeyGBreve: base='г' shift='Г'
    { VK_OEM_5, CAPLOK, { 0x0447, 0x0427 } },  // KeyCCedilla: base='ч' shift='Ч'
    { VK_OEM_7, CAPLOK, { 0x0456, 0x0406 } },  // KeyISlash: base='і' shift='І'
    { 0, 0, { 0, 0 } },  // terminator
};

// aVkToWcharTable[]: groups of VK_TO_WCHARS tables by shift-state
// count. Kitt only has one group (2 shift states: base, shift).
static VK_TO_WCHAR_TABLE kitt_VkToWcharTable[] = {
    { (PVK_TO_WCHARS1)(void*)kitt_VkToWchars2, 2, sizeof(VK_TO_WCHARS2) },
    { NULL, 0, 0 },  // terminator
};

// aDeadKey[]: dead-key combination -> composed character.
// dwBoth = MAKELONG(following_char, accent_char): low word is the
// character typed after the dead key, high word is the dead key's
// own accent ("alone") character.
static DEADKEY kitt_DeadKey[] = {
    DEADTRANS(0x0430, 0x0439, 0x044F, DKF_DEAD),  // Y + KeyA.base ('а') -> 'я'
    DEADTRANS(0x0410, 0x0439, 0x042F, DKF_DEAD),  // Y + KeyA.shift ('А') -> 'Я'
    DEADTRANS(0x0435, 0x0439, 0x0454, DKF_DEAD),  // Y + KeyE.base ('е') -> 'є'
    DEADTRANS(0x0415, 0x0439, 0x0404, DKF_DEAD),  // Y + KeyE.shift ('Е') -> 'Є'
    DEADTRANS(0x0456, 0x0439, 0x0457, DKF_DEAD),  // Y + KeyISlash.base ('і') -> 'ї'
    DEADTRANS(0x0406, 0x0439, 0x0407, DKF_DEAD),  // Y + KeyISlash.shift ('І') -> 'Ї'
    DEADTRANS(0x0443, 0x0439, 0x044E, DKF_DEAD),  // Y + KeyU.base ('у') -> 'ю'
    DEADTRANS(0x0423, 0x0439, 0x042E, DKF_DEAD),  // Y + KeyU.shift ('У') -> 'Ю'
    DEADTRANS(0, 0, 0, 0),  // terminator
};

// aVscToVk[]: standard PC/AT-101 scan-code -> virtual-key table.
// Kitt does not remap physical key positions, only what each VK
// produces, so this table matches an ordinary US/ISO layout.
static USHORT kitt_VscToVk[] = {
    /* 0x00 */ 0,
    /* 0x01 */ VK_ESCAPE,
    /* 0x02 */ '1',
    /* 0x03 */ '2',
    /* 0x04 */ '3',
    /* 0x05 */ '4',
    /* 0x06 */ '5',
    /* 0x07 */ '6',
    /* 0x08 */ '7',
    /* 0x09 */ '8',
    /* 0x0A */ '9',
    /* 0x0B */ '0',
    /* 0x0C */ VK_OEM_8,
    /* 0x0D */ VK_OEM_MINUS,
    /* 0x0E */ VK_BACK,
    /* 0x0F */ VK_TAB,
    /* 0x10 */ 'Q',
    /* 0x11 */ 'W',
    /* 0x12 */ 'E',
    /* 0x13 */ 'R',
    /* 0x14 */ 'T',
    /* 0x15 */ 'Y',
    /* 0x16 */ 'U',
    /* 0x17 */ 'I',
    /* 0x18 */ 'O',
    /* 0x19 */ 'P',
    /* 0x1A */ VK_OEM_4,
    /* 0x1B */ VK_OEM_6,
    /* 0x1C */ VK_RETURN,
    /* 0x1D */ VK_LCONTROL,
    /* 0x1E */ 'A',
    /* 0x1F */ 'S',
    /* 0x20 */ 'D',
    /* 0x21 */ 'F',
    /* 0x22 */ 'G',
    /* 0x23 */ 'H',
    /* 0x24 */ 'J',
    /* 0x25 */ 'K',
    /* 0x26 */ 'L',
    /* 0x27 */ VK_OEM_1,
    /* 0x28 */ VK_OEM_7,
    /* 0x29 */ VK_OEM_3,
    /* 0x2A */ VK_LSHIFT,
    /* 0x2B */ VK_OEM_COMMA,
    /* 0x2C */ 'Z',
    /* 0x2D */ 'X',
    /* 0x2E */ 'C',
    /* 0x2F */ 'V',
    /* 0x30 */ 'B',
    /* 0x31 */ 'N',
    /* 0x32 */ 'M',
    /* 0x33 */ VK_OEM_2,
    /* 0x34 */ VK_OEM_5,
    /* 0x35 */ VK_OEM_PERIOD,
    /* 0x36 */ VK_RSHIFT,
    /* 0x37 */ VK_MULTIPLY,
    /* 0x38 */ VK_LMENU,
    /* 0x39 */ VK_SPACE,
    /* 0x3A */ VK_CAPITAL,
    /* 0x3B */ VK_F1,
    /* 0x3C */ VK_F2,
    /* 0x3D */ VK_F3,
    /* 0x3E */ VK_F4,
    /* 0x3F */ VK_F5,
    /* 0x40 */ VK_F6,
    /* 0x41 */ VK_F7,
    /* 0x42 */ VK_F8,
    /* 0x43 */ VK_F9,
    /* 0x44 */ VK_F10,
    /* 0x45 */ VK_NUMLOCK,
    /* 0x46 */ VK_SCROLL,
    /* 0x47 */ VK_NUMPAD7,
    /* 0x48 */ VK_NUMPAD8,
    /* 0x49 */ VK_NUMPAD9,
    /* 0x4A */ VK_SUBTRACT,
    /* 0x4B */ VK_NUMPAD4,
    /* 0x4C */ VK_NUMPAD5,
    /* 0x4D */ VK_NUMPAD6,
    /* 0x4E */ VK_ADD,
    /* 0x4F */ VK_NUMPAD1,
    /* 0x50 */ VK_NUMPAD2,
    /* 0x51 */ VK_NUMPAD3,
    /* 0x52 */ VK_NUMPAD0,
    /* 0x53 */ VK_DECIMAL,
    /* 0x54 */ 0,
    /* 0x55 */ 0,
    /* 0x56 */ VK_OEM_102,
    /* 0x57 */ VK_F11,
    /* 0x58 */ VK_F12,
};

// aKeyNames[]: display names for keys shown in OS key-name UI.
// Kitt does not rename any key, so this table only has the
// required NULL terminator.
static VSC_LPWSTR kitt_KeyNames[] = {
    { 0, NULL },
};

// Root KBDTABLES struct: ties every table above together. Returned
// by KbdLayerDescriptor() below, per the standard WDK keyboard-
// layout DLL export contract.
static KBDTABLES kitt_KbdTables = {
    &kitt_CharModifiers,              // pCharModifiers
    kitt_VkToWcharTable,        // pVkToWcharTable
    kitt_DeadKey,                        // pDeadKey
    kitt_KeyNames,                // pKeyNames
    NULL,                                    // pKeyNamesExt
    NULL,                                    // pKeyNamesDead
    kitt_VscToVk,                // pusVSCtoVK
    (BYTE)(sizeof(kitt_VscToVk) / sizeof(kitt_VscToVk[0])),  // bMaxVSCtoVK
    NULL,                                    // pVSCtoVK_E0
    NULL,                                    // pVSCtoVK_E1
    0,                                       // fLocaleFlags (no AltGr)
    0,                                       // nLgMax (no ligatures)
    0,                                       // cbLgEntry
    NULL,                                    // pLigature
    0,                                       // dwType
    0,                                       // dwSubType
};

// Standard WDK keyboard-layout DLL export: returns the KBDTABLES
// struct describing this layout. See kbd.def/.def export file for
// the corresponding EXPORTS entry.
__declspec(dllexport) PKBDTABLES WINAPI KbdLayerDescriptor(VOID)
{
    return &kitt_KbdTables;
}

