<#
.SYNOPSIS
    Removes Kitt build/dist output directories.

.DESCRIPTION
    Deletes build/ and dist/ (both already gitignored — see
    KITT_ARCHITECTURE.md section 4/11) so the next ./tools/build.ps1
    run starts from a clean CMake configure. Does not touch generated
    source under src/windows or docs/, since those are checked into
    the repository and regenerated by kittgen, not by this script.

.EXAMPLE
    ./tools/clean.ps1
#>
[CmdletBinding()]
param()

$ErrorActionPreference = "Stop"
Set-StrictMode -Version Latest

$RepoRoot = Split-Path -Parent $PSScriptRoot

$targets = @(
    (Join-Path $RepoRoot "build"),
    (Join-Path $RepoRoot "dist")
)

foreach ($target in $targets) {
    if (Test-Path $target) {
        Write-Host "Removing $target"
        Remove-Item -Recurse -Force -Path $target
    }
    else {
        Write-Host "Skipping $target (does not exist)"
    }
}

Write-Host "Clean complete." -ForegroundColor Green
